<a href="https://colab.research.google.com/github/henryzhou24/IDX-Exchange-Data-Analyst/blob/main/IDX_Exchange_DA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Week 1

In [2]:
import sys

print(sys.version)
print(sys.executable)

3.13.16 (main, Oct  1 2026, 15:40:24) [GCC 13.3.0]
/usr/bin/python3

In [3]:
import pandas as pd

print("Pandas version:", pd.__version__)

Pandas version: 2.2.3

In [4]:
from google.colab import drive

drive.mount('/content/drive')

Mounted at /content/drive

In [5]:
from pathlib import Path

project_dir = Path('/content/drive/MyDrive/IDX-Exchange')
data_dir = project_dir / 'data'

print("Project folder exists:", project_dir.exists())
print("Data folder exists:", data_dir.exists())

Project folder exists: True
Data folder exists: True

In [6]:
files = list(data_dir.iterdir())

print("Number of files:", len(files))

for file in files[:10]:
    print(file.name)

Number of files: 56
CRMLSListing202402.csv
CRMLSListing202401.csv
CRMLSListing202403.csv
CRMLSListing202404.csv
CRMLSListing202406.csv
CRMLSListing202405.csv
CRMLSListing202407.csv
CRMLSListing202408.csv
CRMLSListing202409.csv
CRMLSListing202410.csv

In [7]:
from collections import Counter

extensions = Counter(file.suffix.lower() for file in files)

print(extensions)

Counter({'.csv': 56})

In [8]:
listing_files = sorted(data_dir.glob("CRMLSListing*.csv"))
sold_files = sorted(data_dir.glob("CRMLSSold*.csv"))

print("Listing files:", len(listing_files))
print("Sold files:", len(sold_files))

print("\nListing files:")
for f in listing_files:
    print(f.name)

print("\nSold files:")
for f in sold_files:
    print(f.name)

Listing files: 28
Sold files: 28

Listing files:
CRMLSListing202401.csv
CRMLSListing202402.csv
CRMLSListing202403.csv
CRMLSListing202404.csv
CRMLSListing202405.csv
CRMLSListing202406.csv
CRMLSListing202407.csv
CRMLSListing202408.csv
CRMLSListing202409.csv
CRMLSListing202410.csv
CRMLSListing202411.csv
CRMLSListing202412.csv
CRMLSListing202501.csv
CRMLSListing202502.csv
CRMLSListing202503.csv
CRMLSListing202504.csv
CRMLSListing202505.csv
CRMLSListing202506.csv
CRMLSListing202507.csv
CRMLSListing202508.csv
CRMLSListing202509.csv
CRMLSListing202510.csv
CRMLSListing202511.csv
CRMLSListing202512.csv
CRMLSListing202601.csv
CRMLSListing202602.csv
CRMLSListing202603.csv
CRMLSListing202604.csv

Sold files:
CRMLSSold202401_filled.csv
CRMLSSold202402.csv
CRMLSSold202403_filled.csv
CRMLSSold202404_filled.csv
CRMLSSold202405_filled.csv
CRMLSSold202406_filled.csv
CRMLSSold202407_filled.csv
CRMLSSold202408.csv
CRMLSSold202409.csv
CRMLSSold202410.csv
CRMLSSold202411.csv
CRMLSSold202412.csv
CRMLSSold202501_filled.csv
CRMLSSold202502.csv
CRMLSSold202503.csv
CRMLSSold202504.csv
CRMLSSold202505.csv
CRMLSSold202506.csv
CRMLSSold202507.csv
CRMLSSold202508.csv
CRMLSSold202509.csv
CRMLSSold202510.csv
CRMLSSold202511.csv
CRMLSSold202512.csv
CRMLSSold202601.csv
CRMLSSold202602.csv
CRMLSSold202603.csv
CRMLSSold202604.csv

In [9]:
import pandas as pd

listing_file = listing_files[0]

print("File:", listing_file.name)

df_listing = pd.read_csv(listing_file)

print("Rows:", len(df_listing))
print("Columns:", len(df_listing.columns))

File: CRMLSListing202401.csv
Rows: 27454
Columns: 84

In [10]:
df_listing.head()

,OriginalListPrice,ListingKey,ListAgentEmail,CloseDate,ClosePrice,ListAgentFirstName,ListAgentLastName,Latitude,Longitude,UnparsedAddress,...,MainLevelBedrooms,NewConstructionYN,GarageSpaces,HighSchoolDistrict,PostalCode,BuyerOfficeName.1,AssociationFee,LotSizeSquareFeet,MiddleOrJuniorSchoolDistrict,UnparsedAddress.1
0,90000.0,1075010398,miriamlara03@gmail.com,NaN,NaN,Miriam,Lara,34.097939,-117.909653,1045 N Azusa 61,...,NaN,NaN,2.0,Covina Valley Unified,91722,NaN,0.0,NaN,NaN,1045 N Azusa 61
1,1500000.0,1074974457,janelle@judsonre.com,NaN,NaN,Janelle,Judson,33.121241,-117.081614,NaN,...,NaN,NaN,NaN,NaN,92025,NaN,0.0,NaN,NaN,NaN
2,1340000.0,1074973329,haleh360@Gmail.com,NaN,NaN,Haleh,Dowlatshahi,34.052207,-118.408445,2220 Avenue Of The Stars 2704,...,NaN,False,NaN,NaN,90067,NaN,2105.0,177861.0,NaN,2220 Avenue Of The Stars 2704
3,2500000.0,1074954552,Reneechen@yourhomesoldguaranteed.com,NaN,NaN,Renee,Chen,33.496363,-117.691677,16 Palisades,...,0.0,False,3.0,Capistrano Unified,92677,NaN,254.0,5300.0,NaN,16 Palisades
4,3150000.0,1074936537,anader@dppre.com,NaN,NaN,Margaret,Nader,34.119345,-118.111254,1615 Waverly Road,...,NaN,NaN,2.0,NaN,91108,NaN,NaN,9404.0,NaN,1615 Waverly Road

In [11]:
df_listing.columns.tolist()

['OriginalListPrice',
 'ListingKey',
 'ListAgentEmail',
 'CloseDate',
 'ClosePrice',
 'ListAgentFirstName',
 'ListAgentLastName',
 'Latitude',
 'Longitude',
 'UnparsedAddress',
 'PropertyType',
 'LivingArea',
 'ListPrice',
 'DaysOnMarket',
 'ListOfficeName',
 'BuyerOfficeName',
 'CoListOfficeName',
 'ListAgentFullName',
 'CoListAgentFirstName',
 'CoListAgentLastName',
 'BuyerAgentMlsId',
 'BuyerAgentFirstName',
 'BuyerAgentLastName',
 'FireplacesTotal',
 'AssociationFeeFrequency',
 'AboveGradeFinishedArea',
 'ListingKeyNumeric',
 'MLSAreaMajor',
 'TaxAnnualAmount',
 'CountyOrParish',
 'PropertyType.1',
 'MlsStatus',
 'ElementarySchool',
 'ListAgentFirstName.1',
 'AttachedGarageYN',
 'ParkingTotal',
 'BuilderName',
 'PropertySubType',
 'LotSizeAcres',
 'SubdivisionName',
 'BuyerOfficeAOR',
 'YearBuilt',
 'DaysOnMarket.1',
 'BuyerAgencyCompensationType',
 'StreetNumberNumeric',
 'LivingArea.1',
 'ListingId',
 'BathroomsTotalInteger',
 'City',
 'BuyerAgencyCompensation',
 'TaxYear',
 'BuildingAreaTotal',
 'BedroomsTotal',
 'ContractStatusChangeDate',
 'Longitude.1',
 'ElementarySchoolDistrict',
 'CoBuyerAgentFirstName',
 'PurchaseContractDate',
 'ListingContractDate',
 'BelowGradeFinishedArea',
 'BusinessType',
 'Latitude.1',
 'ListPrice.1',
 'StateOrProvince',
 'CoveredSpaces',
 'MiddleOrJuniorSchool',
 'FireplaceYN',
 'Stories',
 'HighSchool',
 'Levels',
 'ListAgentLastName.1',
 'CloseDate.1',
 'LotSizeDimensions',
 'LotSizeArea',
 'MainLevelBedrooms',
 'NewConstructionYN',
 'GarageSpaces',
 'HighSchoolDistrict',
 'PostalCode',
 'BuyerOfficeName.1',
 'AssociationFee',
 'LotSizeSquareFeet',
 'MiddleOrJuniorSchoolDistrict',
 'UnparsedAddress.1']

In [12]:
df_listing.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27454 entries, 0 to 27453
Data columns (total 84 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   OriginalListPrice             27349 non-null  float64
 1   ListingKey                    27454 non-null  int64
 2   ListAgentEmail                27421 non-null  object
 3   CloseDate                     20136 non-null  object
 4   ClosePrice                    20001 non-null  float64
 5   ListAgentFirstName            27292 non-null  object
 6   ListAgentLastName             27451 non-null  object
 7   Latitude                      22233 non-null  float64
 8   Longitude                     22271 non-null  float64
 9   UnparsedAddress               27393 non-null  object
 10  PropertyType                  27454 non-null  object
 11  LivingArea                    23743 non-null  float64
 12  ListPrice                     27381 non-null  float64
 13  DaysOnMarket                  27454 non-null  int64
 14  ListOfficeName                27454 non-null  object
 15  BuyerOfficeName               19806 non-null  object
 16  CoListOfficeName              5640 non-null   object
 17  ListAgentFullName             27450 non-null  object
 18  CoListAgentFirstName          5591 non-null   object
 19  CoListAgentLastName           5602 non-null   object
 20  BuyerAgentMlsId               20057 non-null  object
 21  BuyerAgentFirstName           19985 non-null  object
 22  BuyerAgentLastName            20080 non-null  object
 23  FireplacesTotal               0 non-null      float64
 24  AssociationFeeFrequency       7831 non-null   object
 25  AboveGradeFinishedArea        0 non-null      float64
 26  ListingKeyNumeric             27454 non-null  int64
 27  MLSAreaMajor                  24798 non-null  object
 28  TaxAnnualAmount               219 non-null    float64
 29  CountyOrParish                27454 non-null  object
 30  PropertyType.1                27454 non-null  object
 31  MlsStatus                     27454 non-null  object
 32  ElementarySchool              2616 non-null   object
 33  ListAgentFirstName.1          27292 non-null  object
 34  AttachedGarageYN              18072 non-null  object
 35  ParkingTotal                  25408 non-null  float64
 36  BuilderName                   950 non-null    object
 37  PropertySubType               23689 non-null  object
 38  LotSizeAcres                  24588 non-null  float64
 39  SubdivisionName               9144 non-null   object
 40  BuyerOfficeAOR                19485 non-null  object
 41  YearBuilt                     24912 non-null  float64
 42  DaysOnMarket.1                27454 non-null  int64
 43  BuyerAgencyCompensationType   27435 non-null  object
 44  StreetNumberNumeric           27333 non-null  float64
 45  LivingArea.1                  23743 non-null  float64
 46  ListingId                     27454 non-null  object
 47  BathroomsTotalInteger         24913 non-null  float64
 48  City                          27408 non-null  object
 49  BuyerAgencyCompensation       27415 non-null  float64
 50  TaxYear                       37 non-null     float64
 51  BuildingAreaTotal             4168 non-null   float64
 52  BedroomsTotal                 23857 non-null  float64
 53  ContractStatusChangeDate      27314 non-null  object
 54  Longitude.1                   22271 non-null  float64
 55  ElementarySchoolDistrict      0 non-null      float64
 56  CoBuyerAgentFirstName         1669 non-null   object
 57  PurchaseContractDate          21281 non-null  object
 58  ListingContractDate           27454 non-null  object
 59  BelowGradeFinishedArea        72 non-null     float64
 60  BusinessType                  227 non-null    object
 61  Latitude.1                    22233 non-null  float64
 62  ListPrice.1                   27381 non-null  float64
 63  StateOrProvince               27452 non-null  object
 64  CoveredSpaces                 0 non-null      float64
 65  MiddleOrJuniorSchool          2662 non-null   object
 66  FireplaceYN                   23126 non-null  object
 67  Stories                       20230 non-null  float64
 68  HighSchool                    3459 non-null   object
 69  Levels                        21929 non-null  object
 70  ListAgentLastName.1           27451 non-null  object
 71  CloseDate.1                   20136 non-null  object
 72  LotSizeDimensions             1507 non-null   object
 73  LotSizeArea                   24701 non-null  float64
 74  MainLevelBedrooms             12990 non-null  float64
 75  NewConstructionYN             23627 non-null  object
 76  GarageSpaces                  22053 non-null  float64
 77  HighSchoolDistrict            16671 non-null  object
 78  PostalCode                    27444 non-null  object
 79  BuyerOfficeName.1             19806 non-null  object
 80  AssociationFee                18889 non-null  float64
 81  LotSizeSquareFeet             24659 non-null  float64
 82  MiddleOrJuniorSchoolDistrict  0 non-null      float64
 83  UnparsedAddress.1             27393 non-null  object
dtypes: float64(32), int64(4), object(48)
memory usage: 17.6+ MB

In [13]:
df_listing.isna().sum().sort_values(ascending=False).head(20)

ElementarySchoolDistrict        27454
CoveredSpaces                   27454
AboveGradeFinishedArea          27454
FireplacesTotal                 27454
MiddleOrJuniorSchoolDistrict    27454
TaxYear                         27417
BelowGradeFinishedArea          27382
TaxAnnualAmount                 27235
BusinessType                    27227
BuilderName                     26504
LotSizeDimensions               25947
CoBuyerAgentFirstName           25785
ElementarySchool                24838
MiddleOrJuniorSchool            24792
HighSchool                      23995
BuildingAreaTotal               23286
CoListAgentFirstName            21863
CoListAgentLastName             21852
CoListOfficeName                21814
AssociationFeeFrequency         19623
dtype: int64

In [14]:
sold_file = sold_files[0]

print("File:", sold_file.name)

df_sold = pd.read_csv(sold_file)

print("Rows:", len(df_sold))
print("Columns:", len(df_sold.columns))

File: CRMLSSold202401_filled.csv
Rows: 17958
Columns: 80

In [15]:
df_sold.head()

,Flooring,ViewYN,WaterfrontYN,BasementYN,PoolPrivateYN,OriginalListPrice,ListingKey,ListAgentEmail,CloseDate,ClosePrice,...,MainLevelBedrooms,NewConstructionYN,GarageSpaces,HighSchoolDistrict,PostalCode,AssociationFee,LotSizeSquareFeet,MiddleOrJuniorSchoolDistrict,latfilled,lonfilled
0,"Carpet,Tile,Wood",True,NaN,NaN,False,499000.0,551985747,jwachter@cbnorcal.com,2024-01-26,240000.0,...,NaN,False,1.0,Other,94401,6472.0,NaN,NaN,True,True
1,NaN,NaN,NaN,NaN,NaN,0.0,535486633,eabrown@lee-associates.com,2024-01-24,950.0,...,NaN,NaN,NaN,NaN,92394,NaN,52320.0,NaN,False,False
2,NaN,True,NaN,NaN,NaN,75000.0,529986282,Joe@9WINWIN.com,2024-01-16,45000.0,...,NaN,False,NaN,NaN,93240,NaN,217364.0,NaN,False,False
3,NaN,True,NaN,NaN,NaN,199000.0,529618166,carolthefinder@yahoo.com,2024-01-08,141500.0,...,NaN,False,NaN,NaN,92308,NaN,217800.0,NaN,False,False
4,NaN,True,NaN,NaN,NaN,19500.0,522614340,jtavisola@tavisola.com,2024-01-17,15000.0,...,NaN,False,NaN,NaN,93544,0.0,108883.0,NaN,False,False

In [16]:
print(df_sold.columns.tolist())

['Flooring', 'ViewYN', 'WaterfrontYN', 'BasementYN', 'PoolPrivateYN', 'OriginalListPrice', 'ListingKey', 'ListAgentEmail', 'CloseDate', 'ClosePrice', 'ListAgentFirstName', 'ListAgentLastName', 'Latitude', 'Longitude', 'UnparsedAddress', 'PropertyType', 'LivingArea', 'ListPrice', 'DaysOnMarket', 'ListOfficeName', 'BuyerOfficeName', 'CoListOfficeName', 'ListAgentFullName', 'CoListAgentFirstName', 'CoListAgentLastName', 'BuyerAgentMlsId', 'BuyerAgentFirstName', 'BuyerAgentLastName', 'FireplacesTotal', 'AssociationFeeFrequency', 'AboveGradeFinishedArea', 'ListingKeyNumeric', 'MLSAreaMajor', 'TaxAnnualAmount', 'CountyOrParish', 'MlsStatus', 'ElementarySchool', 'AttachedGarageYN', 'ParkingTotal', 'BuilderName', 'PropertySubType', 'LotSizeAcres', 'SubdivisionName', 'BuyerOfficeAOR', 'YearBuilt', 'BuyerAgencyCompensationType', 'StreetNumberNumeric', 'ListingId', 'BathroomsTotalInteger', 'City', 'BuyerAgencyCompensation', 'TaxYear', 'BuildingAreaTotal', 'BedroomsTotal', 'ContractStatusChangeDate', 'ElementarySchoolDistrict', 'CoBuyerAgentFirstName', 'PurchaseContractDate', 'ListingContractDate', 'BelowGradeFinishedArea', 'BusinessType', 'StateOrProvince', 'CoveredSpaces', 'MiddleOrJuniorSchool', 'FireplaceYN', 'Stories', 'HighSchool', 'Levels', 'LotSizeDimensions', 'LotSizeArea', 'MainLevelBedrooms', 'NewConstructionYN', 'GarageSpaces', 'HighSchoolDistrict', 'PostalCode', 'AssociationFee', 'LotSizeSquareFeet', 'MiddleOrJuniorSchoolDistrict', 'latfilled', 'lonfilled']

In [17]:
df_sold.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17958 entries, 0 to 17957
Data columns (total 80 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Flooring                      10104 non-null  object
 1   ViewYN                        16198 non-null  object
 2   WaterfrontYN                  10 non-null     object
 3   BasementYN                    265 non-null    object
 4   PoolPrivateYN                 15447 non-null  object
 5   OriginalListPrice             17900 non-null  float64
 6   ListingKey                    17958 non-null  int64
 7   ListAgentEmail                17939 non-null  object
 8   CloseDate                     17958 non-null  object
 9   ClosePrice                    17958 non-null  float64
 10  ListAgentFirstName            17852 non-null  object
 11  ListAgentLastName             17956 non-null  object
 12  Latitude                      17927 non-null  float64
 13  Longitude                     17928 non-null  float64
 14  UnparsedAddress               17922 non-null  object
 15  PropertyType                  17958 non-null  object
 16  LivingArea                    16410 non-null  float64
 17  ListPrice                     17924 non-null  float64
 18  DaysOnMarket                  17958 non-null  int64
 19  ListOfficeName                17958 non-null  object
 20  BuyerOfficeName               17737 non-null  object
 21  CoListOfficeName              3432 non-null   object
 22  ListAgentFullName             17956 non-null  object
 23  CoListAgentFirstName          3407 non-null   object
 24  CoListAgentLastName           3417 non-null   object
 25  BuyerAgentMlsId               17924 non-null  object
 26  BuyerAgentFirstName           17874 non-null  object
 27  BuyerAgentLastName            17955 non-null  object
 28  FireplacesTotal               0 non-null      float64
 29  AssociationFeeFrequency       4933 non-null   object
 30  AboveGradeFinishedArea        0 non-null      float64
 31  ListingKeyNumeric             17958 non-null  int64
 32  MLSAreaMajor                  16220 non-null  object
 33  TaxAnnualAmount               108 non-null    float64
 34  CountyOrParish                17958 non-null  object
 35  MlsStatus                     17958 non-null  object
 36  ElementarySchool              1822 non-null   object
 37  AttachedGarageYN              12508 non-null  object
 38  ParkingTotal                  16743 non-null  float64
 39  BuilderName                   691 non-null    object
 40  PropertySubType               16296 non-null  object
 41  LotSizeAcres                  16100 non-null  float64
 42  SubdivisionName               6187 non-null   object
 43  BuyerOfficeAOR                17450 non-null  object
 44  YearBuilt                     17024 non-null  float64
 45  BuyerAgencyCompensationType   17930 non-null  object
 46  StreetNumberNumeric           17892 non-null  float64
 47  ListingId                     17958 non-null  object
 48  BathroomsTotalInteger         16884 non-null  float64
 49  City                          17939 non-null  object
 50  BuyerAgencyCompensation       17942 non-null  float64
 51  TaxYear                       18 non-null     float64
 52  BuildingAreaTotal             2466 non-null   float64
 53  BedroomsTotal                 16457 non-null  float64
 54  ContractStatusChangeDate      17241 non-null  object
 55  ElementarySchoolDistrict      0 non-null      float64
 56  CoBuyerAgentFirstName         1365 non-null   object
 57  PurchaseContractDate          17536 non-null  object
 58  ListingContractDate           17956 non-null  object
 59  BelowGradeFinishedArea        54 non-null     float64
 60  BusinessType                  66 non-null     object
 61  StateOrProvince               17958 non-null  object
 62  CoveredSpaces                 0 non-null      float64
 63  MiddleOrJuniorSchool          1855 non-null   object
 64  FireplaceYN                   16072 non-null  object
 65  Stories                       14099 non-null  float64
 66  HighSchool                    2464 non-null   object
 67  Levels                        15163 non-null  object
 68  LotSizeDimensions             952 non-null    object
 69  LotSizeArea                   16163 non-null  float64
 70  MainLevelBedrooms             9392 non-null   float64
 71  NewConstructionYN             15653 non-null  object
 72  GarageSpaces                  15361 non-null  float64
 73  HighSchoolDistrict            11835 non-null  object
 74  PostalCode                    17946 non-null  object
 75  AssociationFee                12275 non-null  float64
 76  LotSizeSquareFeet             16146 non-null  float64
 77  MiddleOrJuniorSchoolDistrict  0 non-null      float64
 78  latfilled                     17958 non-null  bool
 79  lonfilled                     17958 non-null  bool
dtypes: bool(2), float64(28), int64(3), object(47)
memory usage: 10.7+ MB

In [18]:
listing_cols = set(df_listing.columns)
sold_cols = set(df_sold.columns)

print("Columns only in Listing:")
print(sorted(list(listing_cols - sold_cols)))

print("\nColumns only in Sold:")
print(sorted(list(sold_cols - listing_cols)))

print("\nCommon columns:", len(listing_cols & sold_cols))

Columns only in Listing:
['BuyerOfficeName.1', 'CloseDate.1', 'DaysOnMarket.1', 'Latitude.1', 'ListAgentFirstName.1', 'ListAgentLastName.1', 'ListPrice.1', 'LivingArea.1', 'Longitude.1', 'PropertyType.1', 'UnparsedAddress.1']

Columns only in Sold:
['BasementYN', 'Flooring', 'PoolPrivateYN', 'ViewYN', 'WaterfrontYN', 'latfilled', 'lonfilled']

Common columns: 73

In [19]:
filled_sold = data_dir / "CRMLSSold202401_filled.csv"
normal_sold = data_dir / "CRMLSSold202402.csv"

df_filled = pd.read_csv(filled_sold)
df_normal = pd.read_csv(normal_sold)

print("202401 filled:")
print(df_filled.shape)

print("\n202402 normal:")
print(df_normal.shape)

202401 filled:
(17958, 80)

202402 normal:
(19925, 78)

In [20]:
print("Filled columns:", len(df_filled.columns))
print("Normal columns:", len(df_normal.columns))

print("\nColumns only in filled:")
print(sorted(list(set(df_filled.columns) - set(df_normal.columns))))

print("\nColumns only in normal:")
print(sorted(list(set(df_normal.columns) - set(df_filled.columns))))

Filled columns: 80
Normal columns: 78

Columns only in filled:
['latfilled', 'lonfilled']

Columns only in normal:
[]

**Check ListingKey uniqueness**

In [21]:
print("Listing rows:", len(df_listing))
print("Unique ListingKey:", df_listing["ListingKey"].nunique())

print("Duplicate ListingKey rows:",
      df_listing["ListingKey"].duplicated().sum())

Listing rows: 27454
Unique ListingKey: 27454
Duplicate ListingKey rows: 0

In [22]:
print("Sold rows:", len(df_sold))
print("Unique ListingKey:", df_sold["ListingKey"].nunique())

print("Duplicate ListingKey rows:",
      df_sold["ListingKey"].duplicated().sum())

Sold rows: 17958
Unique ListingKey: 17958
Duplicate ListingKey rows: 0

**Check whether ListingKey overlaps**

In [23]:
listing_keys = set(df_listing["ListingKey"].dropna())
sold_keys = set(df_sold["ListingKey"].dropna())

overlap = listing_keys & sold_keys

print("Listing keys:", len(listing_keys))
print("Sold keys:", len(sold_keys))
print("Keys appearing in BOTH:", len(overlap))

Listing keys: 27454
Sold keys: 17958
Keys appearing in BOTH: 1977

In [24]:
print(
    "Percentage of Sold records also found in Listing:",
    round(len(overlap) / len(sold_keys) * 100, 2),
    "%"
)

Percentage of Sold records also found in Listing: 11.01 %

**Look at one matching property**

In [25]:
if overlap:
    example_key = next(iter(overlap))

    listing_match = df_listing[
        df_listing["ListingKey"] == example_key
    ]

    sold_match = df_sold[
        df_sold["ListingKey"] == example_key
    ]

    print("Example ListingKey:", example_key)

    print("\n--- LISTING ---")
    display(
        listing_match[
            ["ListingKey", "ListPrice", "OriginalListPrice",
             "ListingContractDate", "CloseDate", "ClosePrice",
             "MlsStatus", "City"]
        ]
    )

    print("\n--- SOLD ---")
    display(
        sold_match[
            ["ListingKey", "ListPrice", "OriginalListPrice",
             "ListingContractDate", "CloseDate", "ClosePrice",
             "MlsStatus", "City"]
        ]
    )

Example ListingKey: 1054105600

--- LISTING ---

,ListingKey,ListPrice,OriginalListPrice,ListingContractDate,CloseDate,ClosePrice,MlsStatus,City
25124,1054105600,3550.0,3550.0,2024-01-04,2024-01-08,3495.0,Closed,Santa Monica

--- SOLD ---

,ListingKey,ListPrice,OriginalListPrice,ListingContractDate,CloseDate,ClosePrice,MlsStatus,City
1718,1054105600,3550.0,3550.0,2024-01-04,2024-01-08,3495.0,Closed,Santa Monica

**Confirm the Residential category**

In [26]:
# Check the PropertyType values in one Listing and one Sold file

print("Listing PropertyType values:")
print(df_listing["PropertyType"].value_counts(dropna=False).head(20))

print("\nSold PropertyType values:")
print(df_sold["PropertyType"].value_counts(dropna=False).head(20))

Listing PropertyType values:
PropertyType
Residential            17007
ResidentialLease        5752
Land                    2145
ResidentialIncome        893
ManufacturedInPark       877
CommercialSale           394
CommercialLease          291
BusinessOpportunity       95
Name: count, dtype: int64

Sold PropertyType values:
PropertyType
Residential            11194
ResidentialLease        4672
Land                     778
ResidentialIncome        524
ManufacturedInPark       515
CommercialSale           127
CommercialLease          126
BusinessOpportunity       22
Name: count, dtype: int64

**Create the output folder**

In [ ]:
output_dir = project_dir / "output"
output_dir.mkdir(parents=True, exist_ok=True)

print("Output folder:", output_dir)
print("Folder exists:", output_dir.exists())

Output folder: /content/drive/MyDrive/IDX-Exchange/output
Folder exists: True

**Combine, filter, and export**

In [ ]:

import pandas as pd
from pathlib import Path

# Discover the monthly source files
listing_files = sorted(data_dir.glob("CRMLSListing*.csv"))
sold_files = sorted(data_dir.glob("CRMLSSold*.csv"))

print(f"Listing files found: {len(listing_files)}")
print(f"Sold files found: {len(sold_files)}")

# Check that we have the expected monthly coverage
assert len(listing_files) == 28, (
    f"Expected 28 Listing files, found {len(listing_files)}"
)
assert len(sold_files) == 28, (
    f"Expected 28 Sold files, found {len(sold_files)}"
)

def process_monthly_files(files, dataset_name, output_filename):
    monthly_data = []
    file_counts = []

    for file in files:
        df = pd.read_csv(file)

        if "PropertyType" not in df.columns:
            raise ValueError(
                f"'PropertyType' missing from {file.name}"
            )

        rows_before = len(df)

        # Filter to the required property category
        residential = df[
            df["PropertyType"].astype("string").str.strip()
            == "Residential"
        ].copy()

        rows_after = len(residential)

        file_counts.append({
            "dataset": dataset_name,
            "filename": file.name,
            "rows_before_filter": rows_before,
            "residential_rows": rows_after,
            "rows_removed": rows_before - rows_after
        })

        monthly_data.append(residential)

    # Combine the filtered monthly files
    combined = pd.concat(monthly_data, ignore_index=True)

    # Save the combined residential dataset
    output_path = output_dir / output_filename
    combined.to_csv(output_path, index=False)

    summary = {
        "dataset": dataset_name,
        "files_processed": len(files),
        "rows_before_filter": sum(
            x["rows_before_filter"] for x in file_counts
        ),
        "residential_rows": len(combined),
        "rows_removed": sum(
            x["rows_removed"] for x in file_counts
        ),
        "columns_in_output": len(combined.columns),
        "output_file": output_filename
    }

    print(f"\n{dataset_name}")
    print("-" * 40)
    print(f"Files processed: {summary['files_processed']:,}")
    print(f"Rows before filtering: {summary['rows_before_filter']:,}")
    print(f"Residential rows: {summary['residential_rows']:,}")
    print(f"Rows removed: {summary['rows_removed']:,}")
    print(f"Output columns: {summary['columns_in_output']:,}")
    print(f"Saved to: {output_path}")

    return combined, summary, file_counts


# Process Listing files
listing_residential, listing_summary, listing_counts = (
    process_monthly_files(
        listing_files,
        "Listing",
        "CRMLSListing_202401_202604_Residential.csv"
    )
)

# Process Sold files
sold_residential, sold_summary, sold_counts = (
    process_monthly_files(
        sold_files,
        "Sold",
        "CRMLSSold_202401_202604_Residential.csv"
    )
)

# Save processing documentation
summary_df = pd.DataFrame([listing_summary, sold_summary])
counts_df = pd.DataFrame(listing_counts + sold_counts)

summary_df.to_csv(
    output_dir / "week1_processing_summary.csv",
    index=False
)
counts_df.to_csv(
    output_dir / "week1_monthly_file_counts.csv",
    index=False
)

display(summary_df)
print("\nWeek 1 processing complete.")

Listing files found: 28
Sold files found: 28

/tmp/ipykernel_1696/1271434387.py:24: DtypeWarning: Columns (32,58,63,66) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)

Listing
----------------------------------------
Files processed: 28
Rows before filtering: 860,898
Residential rows: 547,162
Rows removed: 313,736
Output columns: 84
Saved to: /content/drive/MyDrive/IDX-Exchange/output/CRMLSListing_202401_202604_Residential.csv

/tmp/ipykernel_1696/1271434387.py:24: DtypeWarning: Columns (2,36,39,56,74) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)
/tmp/ipykernel_1696/1271434387.py:24: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)
/tmp/ipykernel_1696/1271434387.py:24: DtypeWarning: Columns (4,74) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)

Sold
----------------------------------------
Files processed: 28
Rows before filtering: 615,707
Residential rows: 414,054
Rows removed: 201,653
Output columns: 84
Saved to: /content/drive/MyDrive/IDX-Exchange/output/CRMLSSold_202401_202604_Residential.csv

,dataset,files_processed,rows_before_filter,residential_rows,rows_removed,columns_in_output,output_file
0,Listing,28,860898,547162,313736,84,CRMLSListing_202401_202604_Residential.csv
1,Sold,28,615707,414054,201653,84,CRMLSSold_202401_202604_Residential.csv

Week 1 processing complete.

**Validate the outputs**

In [27]:
from pathlib import Path
import pandas as pd

project_dir = Path("/content/drive/MyDrive/IDX-Exchange")
output_dir = project_dir / "output"

print("Output folder exists:", output_dir.exists())
print("Output files:", [p.name for p in output_dir.glob("*.csv")])

Output folder exists: True
Output files: ['CRMLSListing_202401_202604_Residential.csv', 'CRMLSSold_202401_202604_Residential.csv', 'week1_processing_summary.csv', 'week1_monthly_file_counts.csv']

In [28]:

import pandas as pd

listing_output = output_dir / "CRMLSListing_202401_202604_Residential.csv"
sold_output = output_dir / "CRMLSSold_202401_202604_Residential.csv"

expected_rows = {
    listing_output.name: 547_162,
    sold_output.name: 414_054
}

for path in [listing_output, sold_output]:
    print(f"\nChecking: {path.name}")
    assert path.exists(), f"File not found: {path}"

    check = pd.read_csv(path, low_memory=False)

    non_residential = (
        check["PropertyType"].astype("string").str.strip() != "Residential"
    ).sum()

    print(f"Rows: {len(check):,}")
    print(f"Columns: {len(check.columns):,}")
    print(f"Non-residential rows: {non_residential:,}")
    print(f"Matches expected row count: {len(check) == expected_rows[path.name]}")

    assert len(check) == expected_rows[path.name], "Unexpected row count"
    assert non_residential == 0, "Non-residential rows remain"

print("\nSUCCESS: Both output files passed validation.")

Checking: CRMLSListing_202401_202604_Residential.csv
Rows: 547,162
Columns: 84
Non-residential rows: 0
Matches expected row count: True

Checking: CRMLSSold_202401_202604_Residential.csv
Rows: 414,054
Columns: 84
Non-residential rows: 0
Matches expected row count: True

SUCCESS: Both output files passed validation.

# Week 2

In [29]:

from pathlib import Path
import pandas as pd

# Project folders in Google Drive
project_dir = Path("/content/drive/MyDrive/IDX-Exchange")
data_dir = project_dir / "data"
output_dir = project_dir / "output"

# Check that the folders exist
print("Project folder exists:", project_dir.exists())
print("Source data folder exists:", data_dir.exists())
print("Output folder exists:", output_dir.exists())

# Check the two Week 1 datasets
listing_path = output_dir / "CRMLSListing_202401_202604_Residential.csv"
sold_path = output_dir / "CRMLSSold_202401_202604_Residential.csv"

for path in [listing_path, sold_path]:
    print(f"\n{path.name}")
    print("Exists:", path.exists())
    if path.exists():
        print(f"File size: {path.stat().st_size / (1024**2):.1f} MB")

print("\nSource CSV count:", len(list(data_dir.glob("*.csv"))))

Project folder exists: True
Source data folder exists: True
Output folder exists: True

CRMLSListing_202401_202604_Residential.csv
Exists: True
File size: 287.0 MB

CRMLSSold_202401_202604_Residential.csv
Exists: True
File size: 225.2 MB

Source CSV count: 56

**2.2-Load the datasets and inspect data quality**

In [31]:

import pandas as pd

listing_path = output_dir / "CRMLSListing_202401_202604_Residential.csv"
sold_path = output_dir / "CRMLSSold_202401_202604_Residential.csv"

# Load the Listing dataset
listing_df = pd.read_csv(listing_path, low_memory=False)

print("LISTING DATASET")
print("=" * 50)
print("Shape:", listing_df.shape)
print("Duplicate rows:", listing_df.duplicated().sum())
print("\nColumn names:")
print(list(listing_df.columns))

LISTING DATASET
==================================================
Shape: (547162, 84)
Duplicate rows: 0

Column names:
['OriginalListPrice', 'ListingKey', 'ListAgentEmail', 'CloseDate', 'ClosePrice', 'ListAgentFirstName', 'ListAgentLastName', 'Latitude', 'Longitude', 'UnparsedAddress', 'PropertyType', 'LivingArea', 'ListPrice', 'DaysOnMarket', 'ListOfficeName', 'BuyerOfficeName', 'CoListOfficeName', 'ListAgentFullName', 'CoListAgentFirstName', 'CoListAgentLastName', 'BuyerAgentMlsId', 'BuyerAgentFirstName', 'BuyerAgentLastName', 'FireplacesTotal', 'AssociationFeeFrequency', 'AboveGradeFinishedArea', 'ListingKeyNumeric', 'MLSAreaMajor', 'TaxAnnualAmount', 'CountyOrParish', 'PropertyType.1', 'MlsStatus', 'ElementarySchool', 'ListAgentFirstName.1', 'AttachedGarageYN', 'ParkingTotal', 'BuilderName', 'PropertySubType', 'LotSizeAcres', 'SubdivisionName', 'BuyerOfficeAOR', 'YearBuilt', 'DaysOnMarket.1', 'BuyerAgencyCompensationType', 'StreetNumberNumeric', 'LivingArea.1', 'ListingId', 'BathroomsTotalInteger', 'City', 'BuyerAgencyCompensation', 'TaxYear', 'BuildingAreaTotal', 'BedroomsTotal', 'ContractStatusChangeDate', 'Longitude.1', 'ElementarySchoolDistrict', 'CoBuyerAgentFirstName', 'PurchaseContractDate', 'ListingContractDate', 'BelowGradeFinishedArea', 'BusinessType', 'Latitude.1', 'ListPrice.1', 'StateOrProvince', 'CoveredSpaces', 'MiddleOrJuniorSchool', 'FireplaceYN', 'Stories', 'HighSchool', 'Levels', 'ListAgentLastName.1', 'CloseDate.1', 'LotSizeDimensions', 'LotSizeArea', 'MainLevelBedrooms', 'NewConstructionYN', 'GarageSpaces', 'HighSchoolDistrict', 'PostalCode', 'BuyerOfficeName.1', 'AssociationFee', 'LotSizeSquareFeet', 'MiddleOrJuniorSchoolDistrict', 'UnparsedAddress.1']

**2.2.1-Check missing values**

In [32]:

# Count missing values and percentages for each column
listing_missing = pd.DataFrame({
    "missing_count": listing_df.isna().sum(),
    "missing_percent": (
        listing_df.isna().mean() * 100
    ).round(2),
    "data_type": listing_df.dtypes.astype(str)
})

listing_missing = listing_missing.sort_values(
    "missing_percent", ascending=False
)

display(listing_missing.head(30))

                              missing_count  missing_percent data_type
TaxYear                              547162           100.00   float64
TaxAnnualAmount                      547162           100.00   float64
AboveGradeFinishedArea               547162           100.00   float64
FireplacesTotal                      547162           100.00   float64
ElementarySchoolDistrict             547162           100.00   float64
BusinessType                         547162           100.00   float64
CoveredSpaces                        547162           100.00   float64
MiddleOrJuniorSchoolDistrict         547162           100.00   float64
BelowGradeFinishedArea               544075            99.44   float64
CoBuyerAgentFirstName                533466            97.50    object
BuilderName                          521800            95.36    object
LotSizeDimensions                    518630            94.79    object
BuildingAreaTotal                    498810            91.16   float64
MiddleOrJuniorSchool                 481661            88.03    object
ElementarySchool                     481686            88.03    object
BuyerAgencyCompensationType          468149            85.56    object
BuyerAgencyCompensation              468169            85.56   float64
HighSchool                           461270            84.30    object
CoListAgentFirstName                 425295            77.73    object
CoListAgentLastName                  424892            77.65    object
CoListOfficeName                     424799            77.64    object
ClosePrice                           409481            74.84   float64
BuyerOfficeAOR                       406788            74.35    object
BuyerOfficeName.1                    397275            72.61    object
BuyerOfficeName                      397275            72.61    object
BuyerAgentFirstName                  395832            72.34    object
BuyerAgentMlsId                      395246            72.24    object
BuyerAgentLastName                   395138            72.22    object
CloseDate                            388096            70.93    object
CloseDate.1                          388096            70.93    object

**2.2.2-Inspect key fields**

In [33]:

key_columns = [
    "ListingKey",
    "PropertyType",
    "ListPrice",
    "ClosePrice",
    "CloseDate",
    "LivingArea",
    "DaysOnMarket",
    "City",
    "MLSAreaMajor",
    "YearBuilt"
]

available_columns = [
    col for col in key_columns
    if col in listing_df.columns
]

display(listing_df[available_columns].head(10))

print("\nMissing values in key fields:")
display(listing_df[available_columns].isna().sum().to_frame(
    "missing_count"
))

,ListingKey,PropertyType,ListPrice,ClosePrice,CloseDate,LivingArea,DaysOnMarket,City,MLSAreaMajor,YearBuilt
0,1074973329,Residential,1340000.0,NaN,NaN,1301.0,127,Los Angeles,C05 - Westwood - Century City,1964.0
1,1074954552,Residential,2500000.0,NaN,NaN,2788.0,1,Laguna Niguel,LNSLT - Salt Creek,1994.0
2,1074936537,Residential,3150000.0,NaN,NaN,3250.0,1,San Marino,655 - San Marino,1965.0
3,1074917818,Residential,3090000.0,NaN,NaN,7456.0,0,Diamond Bar,616 - Diamond Bar,2003.0
4,1074143166,Residential,12725000.0,NaN,NaN,2321.0,2,Newport Beach,N9 - Lower Newport Bay - Balboa Island,2019.0
5,1073349180,Residential,665000.0,NaN,NaN,1487.0,2,Lakeside,92040 - Lakeside,2004.0
6,1073322022,Residential,1125000.0,NaN,NaN,1750.0,2,Rancho Mirage,321 - Rancho Mirage,1972.0
7,1073315828,Residential,1849000.0,NaN,NaN,3152.0,3,La Canada Flintridge,634 - La Canada Flintridge,1949.0
8,1073313770,Residential,1389000.0,NaN,NaN,2282.0,5,Anaheim Hills,77 - Anaheim Hills,1997.0
9,1073295259,Residential,1249888.0,1262555.0,2024-05-01,1899.0,0,San Juan Capistrano,JS - San Juan South,2018.0

Missing values in key fields:

              missing_count
ListingKey                0
PropertyType              0
ListPrice                 0
ClosePrice           409481
CloseDate            388096
LivingArea              552
DaysOnMarket              0
City                    577
MLSAreaMajor          74488
YearBuilt               927

**2.2.3 Investigate duplicate IDs, listing status, and .1 columns**

In [36]:
# 1. Check ListingKey uniqueness
print("LISTING KEY CHECK")
print("Total rows:", len(listing_df))
print("Unique ListingKey values:", listing_df["ListingKey"].nunique())
print("Missing ListingKey values:", listing_df["ListingKey"].isna().sum())
print("Repeated ListingKey rows:",
      listing_df["ListingKey"].duplicated().sum())

# 2. Inspect listing status
print("\nLISTING STATUS DISTRIBUTION")
if "MlsStatus" in listing_df.columns:
    display(
        listing_df["MlsStatus"]
        .value_counts(dropna=False)
        .head(20)
        .to_frame("count")
    )

# 3. Compare columns that have .1 suffixes
print("\nDUPLICATE-NAMED COLUMN COMPARISON")

column_pairs = [
    ("PropertyType", "PropertyType.1"),
    ("DaysOnMarket", "DaysOnMarket.1"),
    ("LivingArea", "LivingArea.1"),
    ("Latitude", "Latitude.1"),
    ("Longitude", "Longitude.1"),
    ("ListPrice", "ListPrice.1"),
    ("CloseDate", "CloseDate.1"),
    ("ListAgentFirstName", "ListAgentFirstName.1"),
    ("ListAgentLastName", "ListAgentLastName.1"),
    ("BuyerOfficeName", "BuyerOfficeName.1"),
    ("UnparsedAddress", "UnparsedAddress.1"),
]

comparison_results = []

for col_a, col_b in column_pairs:
    if col_a not in listing_df.columns or col_b not in listing_df.columns:
        continue

    a = listing_df[col_a]
    b = listing_df[col_b]

    both_present = a.notna() & b.notna()
    equal = a.eq(b) | (a.isna() & b.isna())
    disagreements = (both_present & ~equal).sum()

    comparison_results.append({
        "column_1": col_a,
        "column_2": col_b,
        "both_present_rows": int(both_present.sum()),
        "disagreements_when_both_present": int(disagreements),
        "column_1_missing": int(a.isna().sum()),
        "column_2_missing": int(b.isna().sum())
    })

display(pd.DataFrame(comparison_results))

LISTING KEY CHECK
Total rows: 547162
Unique ListingKey values: 547023
Missing ListingKey values: 0
Repeated ListingKey rows: 139

LISTING STATUS DISTRIBUTION

                      count
MlsStatus
Active               277709
Closed               137676
Pending               87459
ActiveUnderContract   42508
ComingSoon             1810

DUPLICATE-NAMED COLUMN COMPARISON

,column_1,column_2,both_present_rows,disagreements_when_both_present,column_1_missing,column_2_missing
0,PropertyType,PropertyType.1,547162,0,0,0
1,DaysOnMarket,DaysOnMarket.1,547162,0,0,0
2,LivingArea,LivingArea.1,546610,0,552,552
3,Latitude,Latitude.1,466915,0,80247,80247
4,Longitude,Longitude.1,466915,0,80247,80247
5,ListPrice,ListPrice.1,547162,0,0,0
6,CloseDate,CloseDate.1,159066,0,388096,388096
7,ListAgentFirstName,ListAgentFirstName.1,542808,0,4354,4354
8,ListAgentLastName,ListAgentLastName.1,547120,0,42,42
9,BuyerOfficeName,BuyerOfficeName.1,149887,1,397275,397275
10,UnparsedAddress,UnparsedAddress.1,546379,0,782,783

**2.2.4 Investigate the anomalies**

In [37]:
# 1. Investigate repeated ListingKey values
duplicate_rows = listing_df[
    listing_df["ListingKey"].duplicated(keep=False)
].copy()

print("DUPLICATE KEY INVESTIGATION")
print("Rows associated with repeated keys:", len(duplicate_rows))
print("Number of repeated key groups:",
      duplicate_rows["ListingKey"].nunique())

core_fields = [
    "MlsStatus", "ListPrice", "ClosePrice", "CloseDate",
    "ListingContractDate", "LivingArea", "City"
]

available_fields = [
    c for c in core_fields if c in duplicate_rows.columns
]

duplicate_variation = (
    duplicate_rows.groupby("ListingKey")[available_fields]
    .nunique(dropna=False)
)

print("Repeated-key groups with differences in core fields:",
      (duplicate_variation > 1).any(axis=1).sum())

# Show only aggregate results, not property-level records
print("\nNumber of repeated-key groups by status combinations:")
status_combinations = (
    duplicate_rows.groupby("ListingKey")["MlsStatus"]
    .agg(lambda s: " | ".join(sorted(s.dropna().astype(str).unique())))
    .value_counts()
)
display(status_combinations.to_frame("key_group_count").head(15))


# 2. Check closing fields for records marked Closed
print("\nCLOSING FIELD CHECK")

closed = listing_df[
    listing_df["MlsStatus"].astype("string").str.strip().eq("Closed")
]

print("Closed rows:", len(closed))
print("Closed rows missing ClosePrice:", closed["ClosePrice"].isna().sum())
print("Closed rows missing CloseDate:", closed["CloseDate"].isna().sum())

not_closed = listing_df[
    ~listing_df["MlsStatus"].astype("string").str.strip().eq("Closed")
]

print("\nNon-Closed rows with ClosePrice:",
      not_closed["ClosePrice"].notna().sum())
print("Non-Closed rows with CloseDate:",
      not_closed["CloseDate"].notna().sum())


# 3. Inspect the two discrepant column pairs
print("\nCOLUMN PAIR DISCREPANCIES")

for col_a, col_b in [
    ("BuyerOfficeName", "BuyerOfficeName.1"),
    ("UnparsedAddress", "UnparsedAddress.1")
]:
    a = listing_df[col_a]
    b = listing_df[col_b]

    both_present = a.notna() & b.notna()
    different = both_present & a.ne(b)
    missingness_differs = a.isna() != b.isna()

    print(f"\n{col_a} vs {col_b}")
    print("Different where both present:", int(different.sum()))
    print("Different missingness:", int(missingness_differs.sum()))

DUPLICATE KEY INVESTIGATION
Rows associated with repeated keys: 276
Number of repeated key groups: 137
Repeated-key groups with differences in core fields: 137

Number of repeated-key groups by status combinations:

                                  key_group_count
MlsStatus
Active                                         43
Active | ComingSoon                            34
ComingSoon | Pending                           25
Active | Pending                               12
Active | Closed                                 9
Closed | ComingSoon                             6
Active | ActiveUnderContract                    3
ActiveUnderContract | ComingSoon                2
ActiveUnderContract | Pending                   1
Pending                                         1
Closed | Pending                                1

CLOSING FIELD CHECK
Closed rows: 137676
Closed rows missing ClosePrice: 0
Closed rows missing CloseDate: 0

Non-Closed rows with ClosePrice: 5
Non-Closed rows with CloseDate: 21390

COLUMN PAIR DISCREPANCIES

BuyerOfficeName vs BuyerOfficeName.1
Different where both present: 1
Different missingness: 0

UnparsedAddress vs UnparsedAddress.1
Different where both present: 0
Different missingness: 1

**2.3.1 The same checks on the Sold dataset** **bold text**

In [38]:
# Load the Sold dataset
sold_df = pd.read_csv(sold_path, low_memory=False)

print("SOLD DATASET")
print("=" * 50)
print("Shape:", sold_df.shape)
print("Exact duplicate rows:", sold_df.duplicated().sum())

# 1. Check unique keys
print("\nSOLD KEY CHECK")
print("Unique ListingKey values:", sold_df["ListingKey"].nunique())
print("Missing ListingKey values:", sold_df["ListingKey"].isna().sum())
print("Repeated ListingKey rows:",
      sold_df["ListingKey"].duplicated().sum())

# 2. Missing-value report
sold_missing = pd.DataFrame({
    "missing_count": sold_df.isna().sum(),
    "missing_percent": (sold_df.isna().mean() * 100).round(2),
    "data_type": sold_df.dtypes.astype(str)
}).sort_values("missing_percent", ascending=False)

print("\nTOP 25 COLUMNS BY MISSINGNESS")
display(sold_missing.head(25))

# 3. Check status distribution, if available
if "MlsStatus" in sold_df.columns:
    print("\nSOLD STATUS DISTRIBUTION")
    display(
        sold_df["MlsStatus"]
        .value_counts(dropna=False)
        .to_frame("count")
    )

# 4. Check critical sale fields
print("\nSOLD FIELD COMPLETENESS")
for col in [
    "ClosePrice", "CloseDate", "ListPrice",
    "LivingArea", "DaysOnMarket", "City", "MLSAreaMajor"
]:
    if col in sold_df.columns:
        print(f"{col}: {sold_df[col].isna().sum():,} missing "
              f"({sold_df[col].isna().mean() * 100:.2f}%)")

# 5. Compare duplicate-named columns
print("\nSOLD .1 COLUMN COMPARISON")
column_pairs = [
    ("PropertyType", "PropertyType.1"),
    ("DaysOnMarket", "DaysOnMarket.1"),
    ("LivingArea", "LivingArea.1"),
    ("Latitude", "Latitude.1"),
    ("Longitude", "Longitude.1"),
    ("ListPrice", "ListPrice.1"),
    ("CloseDate", "CloseDate.1"),
    ("UnparsedAddress", "UnparsedAddress.1"),
]

results = []

for col_a, col_b in column_pairs:
    if col_a not in sold_df.columns or col_b not in sold_df.columns:
        continue

    a, b = sold_df[col_a], sold_df[col_b]
    both_present = a.notna() & b.notna()

    results.append({
        "column_1": col_a,
        "column_2": col_b,
        "both_present_rows": int(both_present.sum()),
        "disagreements": int((both_present & a.ne(b)).sum()),
        "missingness_differences": int((a.isna() != b.isna()).sum())
    })

display(pd.DataFrame(results))

SOLD DATASET
==================================================
Shape: (414054, 84)
Exact duplicate rows: 48

SOLD KEY CHECK
Unique ListingKey values: 413712
Missing ListingKey values: 0
Repeated ListingKey rows: 342

TOP 25 COLUMNS BY MISSINGNESS

                              missing_count  missing_percent data_type
TaxYear                              414054           100.00   float64
FireplacesTotal                      414054           100.00   float64
TaxAnnualAmount                      414054           100.00   float64
AboveGradeFinishedArea               414054           100.00   float64
ElementarySchoolDistrict             414054           100.00   float64
BusinessType                         414054           100.00   float64
CoveredSpaces                        414054           100.00   float64
MiddleOrJuniorSchoolDistrict         414054           100.00   float64
WaterfrontYN                         413795            99.94    object
BelowGradeFinishedArea               411652            99.42   float64
BasementYN                           405952            98.04    object
LotSizeDimensions                    393945            95.14    object
BuilderName                          393790            95.11    object
BuildingAreaTotal                    385055            93.00   float64
CoBuyerAgentFirstName                376429            90.91    object
OriginatingSystemName                369545            89.25    object
OriginatingSystemSubName             369545            89.25    object
ElementarySchool                     358943            86.69    object
MiddleOrJuniorSchool                 358554            86.60    object
BuyerAgencyCompensation              356739            86.16   float64
BuyerAgencyCompensationType          356726            86.15    object
HighSchool                           341992            82.60    object
CoListAgentFirstName                 319162            77.08    object
CoListAgentLastName                  318916            77.02    object
CoListOfficeName                     316062            76.33    object

SOLD STATUS DISTRIBUTION

            count
MlsStatus
Closed     414054

SOLD FIELD COMPLETENESS
ClosePrice: 2 missing (0.00%)
CloseDate: 0 missing (0.00%)
ListPrice: 0 missing (0.00%)
LivingArea: 234 missing (0.06%)
DaysOnMarket: 0 missing (0.00%)
City: 311 missing (0.08%)
MLSAreaMajor: 55,359 missing (13.37%)

SOLD .1 COLUMN COMPARISON

Empty DataFrame
Columns: []
Index: []

**2.3.2 Investigate the 48 exact duplicates and 342 repeated keys**

In [39]:
# A. Check exact duplicate rows
exact_dup_mask = sold_df.duplicated(keep=False)
exact_dup_groups = sold_df.loc[exact_dup_mask]

print("EXACT DUPLICATE SUMMARY")
print("Duplicate rows beyond first occurrences:",
      int(sold_df.duplicated().sum()))
print("Rows belonging to exact-duplicate groups:",
      int(exact_dup_mask.sum()))
print("ListingKeys represented in those groups:",
      exact_dup_groups["ListingKey"].nunique())

# B. Check repeated ListingKeys
key_counts = sold_df["ListingKey"].value_counts()
repeated_keys = key_counts[key_counts > 1]

print("\nREPEATED KEY SUMMARY")
print("Repeated key groups:", len(repeated_keys))
print("Rows associated with repeated keys:",
      int(repeated_keys.sum()))
print("Largest number of rows for one key:",
      int(repeated_keys.max()))

print("\nRepeated-key group sizes:")
display(
    repeated_keys.value_counts()
    .sort_index()
    .rename_axis("rows_per_key")
    .to_frame("number_of_keys")
)

# C. Check whether repeated-key groups differ on important fields
core_fields = [
    "CloseDate", "ClosePrice", "ListPrice",
    "LivingArea", "DaysOnMarket", "City"
]
core_fields = [c for c in core_fields if c in sold_df.columns]

repeated_records = sold_df[
    sold_df["ListingKey"].isin(repeated_keys.index)
]

variation = (
    repeated_records.groupby("ListingKey")[core_fields]
    .nunique(dropna=False)
)

print("\nREPEATED KEY FIELD VARIATION")
print("Groups differing in at least one core field:",
      int((variation > 1).any(axis=1).sum()))

# D. Check the two missing ClosePrice records without displaying records
print("\nMISSING CLOSE PRICE CHECK")
print("Rows missing ClosePrice:", int(sold_df["ClosePrice"].isna().sum()))
print("Rows missing CloseDate:", int(sold_df["CloseDate"].isna().sum()))

# E. Identify whether any duplicate-suffixed columns exist
suffix_columns = [c for c in sold_df.columns if c.endswith(".1")]
print("\nColumns ending in '.1':", suffix_columns)

EXACT DUPLICATE SUMMARY
Duplicate rows beyond first occurrences: 48
Rows belonging to exact-duplicate groups: 96
ListingKeys represented in those groups: 48

REPEATED KEY SUMMARY
Repeated key groups: 338
Rows associated with repeated keys: 680
Largest number of rows for one key: 3

Repeated-key group sizes:

              number_of_keys
rows_per_key
2                        334
3                          4

REPEATED KEY FIELD VARIATION
Groups differing in at least one core field: 290

MISSING CLOSE PRICE CHECK
Rows missing ClosePrice: 2
Rows missing CloseDate: 0

Columns ending in '.1': []

**2.3.3 Creating a Cleaning Report**

In [40]:
from pathlib import Path
import pandas as pd

# Report findings gathered so far
quality_report = pd.DataFrame([
    {
        "dataset": "Listing",
        "rows": len(listing_df),
        "columns": len(listing_df.columns),
        "exact_duplicate_rows_beyond_first": int(listing_df.duplicated().sum()),
        "repeated_key_groups": int(
            listing_df.loc[
                listing_df["ListingKey"].duplicated(keep=False),
                "ListingKey"
            ].nunique()
        ),
        "missing_ClosePrice": int(listing_df["ClosePrice"].isna().sum()),
        "missing_CloseDate": int(listing_df["CloseDate"].isna().sum()),
        "missing_LivingArea": int(listing_df["LivingArea"].isna().sum()),
        "missing_City": int(listing_df["City"].isna().sum()),
        "missing_MLSAreaMajor": int(listing_df["MLSAreaMajor"].isna().sum()),
        "columns_100pct_missing": int(listing_df.isna().all().sum())
    },
    {
        "dataset": "Sold",
        "rows": len(sold_df),
        "columns": len(sold_df.columns),
        "exact_duplicate_rows_beyond_first": int(sold_df.duplicated().sum()),
        "repeated_key_groups": int(
            sold_df.loc[
                sold_df["ListingKey"].duplicated(keep=False),
                "ListingKey"
            ].nunique()
        ),
        "missing_ClosePrice": int(sold_df["ClosePrice"].isna().sum()),
        "missing_CloseDate": int(sold_df["CloseDate"].isna().sum()),
        "missing_LivingArea": int(sold_df["LivingArea"].isna().sum()),
        "missing_City": int(sold_df["City"].isna().sum()),
        "missing_MLSAreaMajor": int(sold_df["MLSAreaMajor"].isna().sum()),
        "columns_100pct_missing": int(sold_df.isna().all().sum())
    }
])

display(quality_report)

report_path = output_dir / "week2_data_quality_report.csv"
quality_report.to_csv(report_path, index=False)

print("Saved quality report to:", report_path)

,dataset,rows,columns,exact_duplicate_rows_beyond_first,repeated_key_groups,missing_ClosePrice,missing_CloseDate,missing_LivingArea,missing_City,missing_MLSAreaMajor,columns_100pct_missing
0,Listing,547162,84,0,137,409481,388096,552,577,74488,8
1,Sold,414054,84,48,338,2,0,234,311,55359,8

Saved quality report to: /content/drive/MyDrive/IDX-Exchange/output/week2_data_quality_report.csv

**Week 2 Deliverable**

In [41]:
%%writefile /content/drive/MyDrive/IDX-Exchange/week2_3_deliverable.py

from pathlib import Path
import pandas as pd

# ============================================================
# IDX Exchange Data Analyst Internship — Weeks 2–3 Deliverable
# ============================================================
# Inputs:
#   data/   : Original CRMLS monthly CSV files
#   output/ : Week 1 residential-filtered Listing and Sold CSVs
#
# Filtering logic:
#   1. Week 1 files contain records where PropertyType is
#      "Residential" (after trimming surrounding whitespace).
#   2. For the new Sold analysis dataset, retain residential
#      records, remove exact duplicate rows, and retain only
#      records with a positive ClosePrice and a valid CloseDate.
#   3. Do NOT remove repeated ListingKeys automatically:
#      different records with the same key may contain
#      meaningful differences.
#
# Raw and processed real estate data should not be uploaded
# to the public GitHub repository.
# ============================================================

PROJECT_DIR = Path("/content/drive/MyDrive/IDX-Exchange")
DATA_DIR = PROJECT_DIR / "data"
OUTPUT_DIR = PROJECT_DIR / "output"

LISTING_PATH = (
    OUTPUT_DIR / "CRMLSListing_202401_202604_Residential.csv"
)
SOLD_PATH = (
    OUTPUT_DIR / "CRMLSSold_202401_202604_Residential.csv"
)

OUTPUT_DIR.mkdir(parents=True, exist_ok=True)


def load_csv(path):
    """Read a CSV while avoiding mixed-type inference warnings."""
    if not path.exists():
        raise FileNotFoundError(f"Required input file not found: {path}")
    return pd.read_csv(path, low_memory=False)


# ------------------------------------------------------------
# 1. Identify property types in the original source files
# ------------------------------------------------------------

type_series = []

source_files = sorted(DATA_DIR.glob("CRMLS*.csv"))

if not source_files:
    raise FileNotFoundError(
        f"No original CRMLS CSV files found in {DATA_DIR}"
    )

for file_path in source_files:
    try:
        types_df = pd.read_csv(
            file_path,
            usecols=["PropertyType"],
            dtype="string",
            low_memory=False
        )

        values = (
            types_df["PropertyType"]
            .str.strip()
            .replace("", pd.NA)
            .dropna()
        )

        type_series.append(values)

    except ValueError:
        print(f"WARNING: PropertyType column not found in {file_path.name}")

if type_series:
    all_types = pd.concat(type_series, ignore_index=True)

    property_type_report = (
        all_types.value_counts()
        .rename_axis("PropertyType")
        .reset_index(name="row_count")
    )

    property_type_report.to_csv(
        OUTPUT_DIR / "week2_3_unique_property_types.csv",
        index=False
    )

    print("\nUnique PropertyType values found in source data:")
    print(property_type_report.to_string(index=False))
else:
    raise ValueError("Could not find PropertyType in the source files.")


# ------------------------------------------------------------
# 2. Load the Week 1 residential-filtered datasets
# ------------------------------------------------------------

listing_df = load_csv(LISTING_PATH)
sold_df = load_csv(SOLD_PATH)

for name, df in [("Listing", listing_df), ("Sold", sold_df)]:
    if "PropertyType" not in df.columns:
        raise KeyError(f"{name} dataset has no PropertyType column.")

    unexpected = (
        df["PropertyType"].astype("string").str.strip().ne("Residential")
    )

    if unexpected.any():
        raise ValueError(
            f"{name} dataset contains {int(unexpected.sum())} "
            "rows that are not PropertyType == 'Residential'."
        )


# ------------------------------------------------------------
# 3. Create a NEW filtered Sold dataset for sale-price analysis
# ------------------------------------------------------------

# Keep the Week 1 source file unchanged.
sold_filtered = sold_df.copy()

# Remove exact duplicate rows only; do not deduplicate by ListingKey.
rows_before = len(sold_filtered)
sold_filtered = sold_filtered.drop_duplicates().copy()
exact_duplicates_removed = rows_before - len(sold_filtered)

# Parse dates and prices for reliable filtering.
sold_filtered["CloseDate"] = pd.to_datetime(
    sold_filtered["CloseDate"], errors="coerce"
)

sold_filtered["ClosePrice"] = pd.to_numeric(
    sold_filtered["ClosePrice"], errors="coerce"
)

# Exclude records without a valid sale price or closing date.
valid_sale = (
    sold_filtered["ClosePrice"].gt(0)
    & sold_filtered["CloseDate"].notna()
)

invalid_sale_rows_removed = int((~valid_sale).sum())
sold_filtered = sold_filtered.loc[valid_sale].copy()

FILTERED_SOLD_PATH = (
    OUTPUT_DIR
    / "CRMLSSold_202401_202604_Residential_AnalysisFiltered.csv"
)

sold_filtered.to_csv(FILTERED_SOLD_PATH, index=False)

print("\nSold dataset filtering:")
print(f"Rows before filtering: {rows_before:,}")
print(f"Exact duplicate rows removed: {exact_duplicates_removed:,}")
print(f"Rows removed for invalid price/date: {invalid_sale_rows_removed:,}")
print(f"Rows in new filtered dataset: {len(sold_filtered):,}")
print(f"Saved to: {FILTERED_SOLD_PATH}")


# ------------------------------------------------------------
# 4. Generate null-count summary tables
# ------------------------------------------------------------

datasets = {
    "Listing": listing_df,
    "Sold": sold_df,
    "Filtered Sold": sold_filtered
}

null_summary_rows = []

for dataset_name, df in datasets.items():
    null_counts = df.isna().sum()

    for column in df.columns:
        null_count = int(null_counts[column])

        null_summary_rows.append({
            "dataset": dataset_name,
            "column": column,
            "row_count": len(df),
            "null_count": null_count,
            "non_null_count": int(len(df) - null_count),
            "null_percentage": round(
                null_count / len(df) * 100, 4
            ) if len(df) else 0
        })

null_summary = pd.DataFrame(null_summary_rows)

null_summary_path = OUTPUT_DIR / "week2_3_null_count_summary.csv"
null_summary.to_csv(null_summary_path, index=False)


# ------------------------------------------------------------
# 5. Flag every column with MORE THAN 90% missing values
# ------------------------------------------------------------

missing_over_90 = null_summary.loc[
    null_summary["null_percentage"] > 90
].copy()

missing_report_path = (
    OUTPUT_DIR / "week2_3_missing_over_90_percent.csv"
)
missing_over_90.to_csv(missing_report_path, index=False)

print("\nColumns with more than 90% missing values:")
if missing_over_90.empty:
    print("None.")
else:
    print(
        missing_over_90[
            ["dataset", "column", "null_count", "null_percentage"]
        ].to_string(index=False)
    )


# ------------------------------------------------------------
# 6. Numeric distribution summary for the required variables
# ------------------------------------------------------------

# Sale-price analysis uses the new filtered Sold dataset.
# For each metric, null/non-numeric values are excluded from
# its statistics. Other numeric values are not silently removed.

numeric_columns = [
    "ClosePrice",
    "LivingArea",
    "DaysOnMarket"
]

distribution_rows = []

for column in numeric_columns:
    if column not in sold_filtered.columns:
        print(f"WARNING: {column} not found; skipping.")
        continue

    values = pd.to_numeric(
        sold_filtered[column], errors="coerce"
    ).dropna()

    if values.empty:
        distribution_rows.append({
            "variable": column,
            "valid_count": 0,
            "min": None,
            "max": None,
            "mean": None,
            "median": None,
            "p1": None,
            "p5": None,
            "p25": None,
            "p50": None,
            "p75": None,
            "p95": None,
            "p99": None
        })
        continue

    distribution_rows.append({
        "variable": column,
        "valid_count": int(values.count()),
        "min": values.min(),
        "max": values.max(),
        "mean": values.mean(),
        "median": values.median(),
        "p1": values.quantile(0.01),
        "p5": values.quantile(0.05),
        "p25": values.quantile(0.25),
        "p50": values.quantile(0.50),
        "p75": values.quantile(0.75),
        "p95": values.quantile(0.95),
        "p99": values.quantile(0.99)
    })

distribution_summary = pd.DataFrame(distribution_rows)

distribution_path = (
    OUTPUT_DIR / "week2_3_numeric_distribution_summary.csv"
)
distribution_summary.to_csv(distribution_path, index=False)

print("\nNumeric distribution summary:")
print(distribution_summary.to_string(index=False))

print("\nAll deliverable files saved:")
for path in [
    OUTPUT_DIR / "week2_3_unique_property_types.csv",
    null_summary_path,
    missing_report_path,
    distribution_path,
    FILTERED_SOLD_PATH
]:
    print(f"- {path}")

Writing /content/drive/MyDrive/IDX-Exchange/week2_3_deliverable.py

In [42]:
!python /content/drive/MyDrive/IDX-Exchange/week2_3_deliverable.py

Unique PropertyType values found in source data:
       PropertyType  row_count
        Residential     961216
   ResidentialLease     319700
               Land      76319
  ResidentialIncome      48354
 ManufacturedInPark      41356
     CommercialSale      15525
    CommercialLease      10974
BusinessOpportunity       3161

Sold dataset filtering:
Rows before filtering: 414,054
Exact duplicate rows removed: 48
Rows removed for invalid price/date: 3
Rows in new filtered dataset: 414,003
Saved to: /content/drive/MyDrive/IDX-Exchange/output/CRMLSSold_202401_202604_Residential_AnalysisFiltered.csv

Columns with more than 90% missing values:
      dataset                       column  null_count  null_percentage
      Listing              FireplacesTotal      547162         100.0000
      Listing       AboveGradeFinishedArea      547162         100.0000
      Listing              TaxAnnualAmount      547162         100.0000
      Listing                  BuilderName      521800          95.3648
      Listing                      TaxYear      547162         100.0000
      Listing            BuildingAreaTotal      498810          91.1631
      Listing     ElementarySchoolDistrict      547162         100.0000
      Listing        CoBuyerAgentFirstName      533466          97.4969
      Listing       BelowGradeFinishedArea      544075          99.4358
      Listing                 BusinessType      547162         100.0000
      Listing                CoveredSpaces      547162         100.0000
      Listing            LotSizeDimensions      518630          94.7855
      Listing MiddleOrJuniorSchoolDistrict      547162         100.0000
         Sold                 WaterfrontYN      413795          99.9374
         Sold                   BasementYN      405952          98.0433
         Sold              FireplacesTotal      414054         100.0000
         Sold       AboveGradeFinishedArea      414054         100.0000
         Sold              TaxAnnualAmount      414054         100.0000
         Sold                  BuilderName      393790          95.1060
         Sold                      TaxYear      414054         100.0000
         Sold            BuildingAreaTotal      385055          92.9963
         Sold     ElementarySchoolDistrict      414054         100.0000
         Sold        CoBuyerAgentFirstName      376429          90.9130
         Sold       BelowGradeFinishedArea      411652          99.4199
         Sold                 BusinessType      414054         100.0000
         Sold                CoveredSpaces      414054         100.0000
         Sold            LotSizeDimensions      393945          95.1434
         Sold MiddleOrJuniorSchoolDistrict      414054         100.0000
Filtered Sold                 WaterfrontYN      413744          99.9374
Filtered Sold                   BasementYN      405902          98.0433
Filtered Sold              FireplacesTotal      414003         100.0000
Filtered Sold       AboveGradeFinishedArea      414003         100.0000
Filtered Sold              TaxAnnualAmount      414003         100.0000
Filtered Sold                  BuilderName      393740          95.1056
Filtered Sold                      TaxYear      414003         100.0000
Filtered Sold            BuildingAreaTotal      385004          92.9955
Filtered Sold     ElementarySchoolDistrict      414003         100.0000
Filtered Sold        CoBuyerAgentFirstName      376382          90.9129
Filtered Sold       BelowGradeFinishedArea      411601          99.4198
Filtered Sold                 BusinessType      414003         100.0000
Filtered Sold                CoveredSpaces      414003         100.0000
Filtered Sold            LotSizeDimensions      393895          95.1430
Filtered Sold MiddleOrJuniorSchoolDistrict      414003         100.0000

Numeric distribution summary:
    variable  valid_count     min         max         mean   median       p1       p5      p25      p50       p75       p95       p99
  ClosePrice       414003    1.15 989500000.0 1.193847e+06 823000.0 202402.0 340000.0 575000.0 823000.0 1300000.0 2850000.0 5572900.0
  LivingArea       413769    0.00  17021321.0 1.903755e+03   1642.0    604.0    840.0   1248.0   1642.0    2219.0    3559.0    5282.0
DaysOnMarket       414003 -288.00     12430.0 3.735322e+01     18.0      0.0      1.0      8.0     18.0      48.0     132.0     231.0

All deliverable files saved:
- /content/drive/MyDrive/IDX-Exchange/output/week2_3_unique_property_types.csv
- /content/drive/MyDrive/IDX-Exchange/output/week2_3_null_count_summary.csv
- /content/drive/MyDrive/IDX-Exchange/output/week2_3_missing_over_90_percent.csv
- /content/drive/MyDrive/IDX-Exchange/output/week2_3_numeric_distribution_summary.csv
- /content/drive/MyDrive/IDX-Exchange/output/CRMLSSold_202401_202604_Residential_AnalysisFiltered.csv

In [43]:
from pathlib import Path

output_dir = Path("/content/drive/MyDrive/IDX-Exchange/output")

required_files = [
    "week2_3_unique_property_types.csv",
    "week2_3_null_count_summary.csv",
    "week2_3_missing_over_90_percent.csv",
    "week2_3_numeric_distribution_summary.csv",
    "CRMLSSold_202401_202604_Residential_AnalysisFiltered.csv",
]

for filename in required_files:
    path = output_dir / filename
    print(f"{'OK' if path.exists() else 'MISSING'}: {filename}")

OK: week2_3_unique_property_types.csv
OK: week2_3_null_count_summary.csv
OK: week2_3_missing_over_90_percent.csv
OK: week2_3_numeric_distribution_summary.csv
OK: CRMLSSold_202401_202604_Residential_AnalysisFiltered.csv

In [44]:
import pandas as pd
from pathlib import Path

output_dir = Path("/content/drive/MyDrive/IDX-Exchange/output")
filtered_path = output_dir / (
    "CRMLSSold_202401_202604_Residential_AnalysisFiltered.csv"
)

df = pd.read_csv(filtered_path, low_memory=False)

# Convert required fields to numeric for checking.
for col in ["ClosePrice", "LivingArea", "DaysOnMarket"]:
    df[col] = pd.to_numeric(df[col], errors="coerce")

checks = {
    "ClosePrice <= 0": df["ClosePrice"] <= 0,
    "ClosePrice > $50 million": df["ClosePrice"] > 50_000_000,
    "LivingArea <= 0": df["LivingArea"] <= 0,
    "LivingArea > 50,000 sq ft": df["LivingArea"] > 50_000,
    "DaysOnMarket < 0": df["DaysOnMarket"] < 0,
    "DaysOnMarket > 3,650 days": df["DaysOnMarket"] > 3650,
}

print("Counts for values requiring review:")
for label, mask in checks.items():
    print(f"{label}: {int(mask.fillna(False).sum()):,}")

# Display examples for investigation, not automatic deletion.
review_mask = (
    (df["ClosePrice"] > 50_000_000)
    | (df["LivingArea"] <= 0)
    | (df["LivingArea"] > 50_000)
    | (df["DaysOnMarket"] < 0)
    | (df["DaysOnMarket"] > 3650)
)

columns_to_show = [
    c for c in [
        "ListingKey", "PropertyType", "City", "CloseDate",
        "ClosePrice", "LivingArea", "DaysOnMarket"
    ] if c in df.columns
]

print("\nExamples to review:")
display(df.loc[review_mask, columns_to_show].head(20))

Counts for values requiring review:
ClosePrice <= 0: 0
ClosePrice > $50 million: 48
LivingArea <= 0: 150
LivingArea > 50,000 sq ft: 4
DaysOnMarket < 0: 48
DaysOnMarket > 3,650 days: 1

Examples to review:

,ListingKey,PropertyType,City,CloseDate,ClosePrice,LivingArea,DaysOnMarket
4,1063453216,Residential,Fort Bragg,2024-01-22,1950000.0,2100.0,-36
393,1054197723,Residential,La Quinta,2024-01-19,655000.0,3045.0,-1
7702,1046380894,Residential,Beverly Hills,2024-01-22,8000000.0,0.0,62
11205,1062122119,Residential,Indian Wells,2024-02-26,899000.0,2533.0,-13
11372,1061302766,Residential,Riverside,2024-02-23,372000.0,1488.0,-10
18689,1052574395,Residential,Oxnard,2024-02-05,700000.0,1382.0,-10
21090,1046973939,Residential,Malibu,2024-02-09,9000000.0,0.0,76
22959,1045698780,Residential,Los Angeles,2024-02-23,1930000.0,0.0,128
22960,1045698270,Residential,Los Angeles,2024-02-23,1850000.0,0.0,94
22996,1045653374,Residential,Beaumont,2024-02-29,476985.0,1342.0,-13
24388,1063549350,Residential,Ojai,2024-03-21,799000.0,1284.0,-48
24396,1063528331,Residential,Fort Bragg,2024-03-19,810000.0,1164.0,-58
24432,1063458939,Residential,Ventura,2024-03-15,880000.0,2018.0,-14
29416,1060256290,Residential,Camarillo,2024-03-08,875000.0,1987.0,-2
30167,1060153479,Residential,La Crescenta,2024-03-21,1625000.0,2130.0,-1
30259,1060140950,Residential,Santa Fe Springs,2024-03-22,780000.0,1490.0,-6
35250,1055059543,Residential,San Diego,2024-03-18,615000.0,920.0,-3
35334,1054697515,Residential,Santa Barbara,2024-03-21,1730000.0,0.0,51
35564,1054201667,Residential,Thousand Oaks,2024-03-04,390000.0,722.0,-2
35917,1054117211,Residential,Colton,2024-03-13,505000.0,1442.0,-5

In [45]:
%%writefile -a /content/drive/MyDrive/IDX-Exchange/week2_3_deliverable.py

# ============================================================
# 7. Numeric Distribution Review: Listing and Sold
# ============================================================

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

NUMERIC_FIELDS = [
    "ClosePrice",
    "ListPrice",
    "OriginalListPrice",
    "LivingArea",
    "LotSizeAcres",
    "BedroomsTotal",
    "BathroomsTotalInteger",
    "DaysOnMarket",
    "YearBuilt"
]

# Create a separate residential analysis copy of Listing.
# Do not remove listings merely because ClosePrice is missing:
# active and pending listings may not have a closing price.
listing_analysis = listing_df.copy()

listing_analysis = listing_analysis.loc[
    listing_analysis["PropertyType"]
    .astype("string").str.strip().eq("Residential")
].drop_duplicates().copy()

listing_analysis_path = (
    OUTPUT_DIR
    / "CRMLSListing_202401_202604_Residential_AnalysisFiltered.csv"
)
listing_analysis.to_csv(listing_analysis_path, index=False)

# Rebuild the Sold analysis copy using the documented rules.
sold_analysis = sold_df.copy()

sold_analysis = sold_analysis.loc[
    sold_analysis["PropertyType"]
    .astype("string").str.strip().eq("Residential")
].drop_duplicates().copy()

sold_analysis["CloseDate"] = pd.to_datetime(
    sold_analysis["CloseDate"], errors="coerce"
)
sold_analysis["ClosePrice"] = pd.to_numeric(
    sold_analysis["ClosePrice"], errors="coerce"
)

sold_analysis = sold_analysis.loc[
    sold_analysis["ClosePrice"].gt(0)
    & sold_analysis["CloseDate"].notna()
].copy()

sold_analysis_path = (
    OUTPUT_DIR
    / "CRMLSSold_202401_202604_Residential_AnalysisFiltered.csv"
)
sold_analysis.to_csv(sold_analysis_path, index=False)

analysis_datasets = {
    "Listing": listing_analysis,
    "Sold": sold_analysis
}

# Save a fresh null-count summary for both original residential
# datasets and both final analysis datasets.
null_rows = []

for dataset_name, frame in {
    "Listing": listing_df,
    "Sold": sold_df,
    "Filtered Listing": listing_analysis,
    "Filtered Sold": sold_analysis
}.items():
    for column in frame.columns:
        null_count = int(frame[column].isna().sum())
        null_rows.append({
            "dataset": dataset_name,
            "column": column,
            "row_count": len(frame),
            "null_count": null_count,
            "non_null_count": len(frame) - null_count,
            "null_percentage": (
                round(100 * null_count / len(frame), 4)
                if len(frame) else 0
            )
        })

null_summary = pd.DataFrame(null_rows)
null_summary.to_csv(
    OUTPUT_DIR / "week2_3_null_count_summary.csv", index=False
)

missing_over_90 = null_summary.loc[
    null_summary["null_percentage"] > 90
].copy()
missing_over_90.to_csv(
    OUTPUT_DIR / "week2_3_missing_over_90_percent.csv",
    index=False
)

# Distribution summaries, IQR outlier counts, and plots.
plot_dir = OUTPUT_DIR / "week2_3_numeric_plots"
plot_dir.mkdir(parents=True, exist_ok=True)

distribution_rows = []
outlier_rows = []

for dataset_name, frame in analysis_datasets.items():
    for column in NUMERIC_FIELDS:
        if column not in frame.columns:
            print(f"WARNING: {dataset_name} is missing {column}")
            continue

        values = pd.to_numeric(
            frame[column], errors="coerce"
        ).dropna()

        if values.empty:
            print(f"WARNING: No numeric values for {dataset_name}: {column}")
            continue

        q1 = values.quantile(0.25)
        median = values.quantile(0.50)
        q3 = values.quantile(0.75)
        iqr = q3 - q1
        lower_fence = q1 - 1.5 * iqr
        upper_fence = q3 + 1.5 * iqr

        distribution_rows.append({
            "dataset": dataset_name,
            "variable": column,
            "valid_count": int(values.count()),
            "null_count": int(frame[column].isna().sum()),
            "min": values.min(),
            "max": values.max(),
            "mean": values.mean(),
            "median": median,
            "p1": values.quantile(0.01),
            "p5": values.quantile(0.05),
            "p25": q1,
            "p50": median,
            "p75": q3,
            "p95": values.quantile(0.95),
            "p99": values.quantile(0.99)
        })

        below = values < lower_fence
        above = values > upper_fence

        outlier_rows.append({
            "dataset": dataset_name,
            "variable": column,
            "q1": q1,
            "q3": q3,
            "iqr": iqr,
            "lower_iqr_fence": lower_fence,
            "upper_iqr_fence": upper_fence,
            "outliers_below": int(below.sum()),
            "outliers_above": int(above.sum()),
            "total_iqr_outliers": int(below.sum() + above.sum()),
            "smallest_value": values.min(),
            "largest_value": values.max()
        })

        # For readability, plots display the central 98% of values.
        # Full-data min/max and IQR outlier counts are retained above.
        p1 = values.quantile(0.01)
        p99 = values.quantile(0.99)
        plot_values = values.loc[values.between(p1, p99)]

        safe_name = (
            f"{dataset_name.lower().replace(' ', '_')}_{column}"
        )

        # Histogram
        fig, ax = plt.subplots(figsize=(8, 5))
        ax.hist(plot_values, bins=40)
        ax.set_title(
            f"{dataset_name}: {column} Histogram "
            "(central 98% shown)"
        )
        ax.set_xlabel(column)
        ax.set_ylabel("Frequency")
        fig.tight_layout()
        fig.savefig(plot_dir / f"{safe_name}_histogram.png", dpi=120)
        plt.close(fig)

        # Boxplot
        fig, ax = plt.subplots(figsize=(8, 5))
        ax.boxplot(plot_values, vert=True, showfliers=False)
        ax.set_title(
            f"{dataset_name}: {column} Boxplot "
            "(central 98% shown)"
        )
        ax.set_ylabel(column)
        fig.tight_layout()
        fig.savefig(plot_dir / f"{safe_name}_boxplot.png", dpi=120)
        plt.close(fig)

distribution_summary = pd.DataFrame(distribution_rows)
distribution_summary.to_csv(
    OUTPUT_DIR / "week2_3_numeric_distribution_summary.csv",
    index=False
)

outlier_report = pd.DataFrame(outlier_rows)
outlier_report.to_csv(
    OUTPUT_DIR / "week2_3_numeric_outlier_flags.csv",
    index=False
)

print("\nAnalysis dataset row counts:")
print(f"Filtered Listing: {len(listing_analysis):,}")
print(f"Filtered Sold: {len(sold_analysis):,}")

print("\nNumeric distribution summary:")
print(distribution_summary.to_string(index=False))

print("\nIQR outlier review:")
print(outlier_report.to_string(index=False))

print("\nUpdated deliverables:")
print(f"- {listing_analysis_path}")
print(f"- {sold_analysis_path}")
print(f"- {OUTPUT_DIR / 'week2_3_null_count_summary.csv'}")
print(f"- {OUTPUT_DIR / 'week2_3_missing_over_90_percent.csv'}")
print(f"- {OUTPUT_DIR / 'week2_3_numeric_distribution_summary.csv'}")
print(f"- {OUTPUT_DIR / 'week2_3_numeric_outlier_flags.csv'}")
print(f"- {plot_dir} (histograms and boxplots)")

Appending to /content/drive/MyDrive/IDX-Exchange/week2_3_deliverable.py

In [46]:
!python /content/drive/MyDrive/IDX-Exchange/week2_3_deliverable.py

Unique PropertyType values found in source data:
       PropertyType  row_count
        Residential     961216
   ResidentialLease     319700
               Land      76319
  ResidentialIncome      48354
 ManufacturedInPark      41356
     CommercialSale      15525
    CommercialLease      10974
BusinessOpportunity       3161

Sold dataset filtering:
Rows before filtering: 414,054
Exact duplicate rows removed: 48
Rows removed for invalid price/date: 3
Rows in new filtered dataset: 414,003
Saved to: /content/drive/MyDrive/IDX-Exchange/output/CRMLSSold_202401_202604_Residential_AnalysisFiltered.csv

Columns with more than 90% missing values:
      dataset                       column  null_count  null_percentage
      Listing              FireplacesTotal      547162         100.0000
      Listing       AboveGradeFinishedArea      547162         100.0000
      Listing              TaxAnnualAmount      547162         100.0000
      Listing                  BuilderName      521800          95.3648
      Listing                      TaxYear      547162         100.0000
      Listing            BuildingAreaTotal      498810          91.1631
      Listing     ElementarySchoolDistrict      547162         100.0000
      Listing        CoBuyerAgentFirstName      533466          97.4969
      Listing       BelowGradeFinishedArea      544075          99.4358
      Listing                 BusinessType      547162         100.0000
      Listing                CoveredSpaces      547162         100.0000
      Listing            LotSizeDimensions      518630          94.7855
      Listing MiddleOrJuniorSchoolDistrict      547162         100.0000
         Sold                 WaterfrontYN      413795          99.9374
         Sold                   BasementYN      405952          98.0433
         Sold              FireplacesTotal      414054         100.0000
         Sold       AboveGradeFinishedArea      414054         100.0000
         Sold              TaxAnnualAmount      414054         100.0000
         Sold                  BuilderName      393790          95.1060
         Sold                      TaxYear      414054         100.0000
         Sold            BuildingAreaTotal      385055          92.9963
         Sold     ElementarySchoolDistrict      414054         100.0000
         Sold        CoBuyerAgentFirstName      376429          90.9130
         Sold       BelowGradeFinishedArea      411652          99.4199
         Sold                 BusinessType      414054         100.0000
         Sold                CoveredSpaces      414054         100.0000
         Sold            LotSizeDimensions      393945          95.1434
         Sold MiddleOrJuniorSchoolDistrict      414054         100.0000
Filtered Sold                 WaterfrontYN      413744          99.9374
Filtered Sold                   BasementYN      405902          98.0433
Filtered Sold              FireplacesTotal      414003         100.0000
Filtered Sold       AboveGradeFinishedArea      414003         100.0000
Filtered Sold              TaxAnnualAmount      414003         100.0000
Filtered Sold                  BuilderName      393740          95.1056
Filtered Sold                      TaxYear      414003         100.0000
Filtered Sold            BuildingAreaTotal      385004          92.9955
Filtered Sold     ElementarySchoolDistrict      414003         100.0000
Filtered Sold        CoBuyerAgentFirstName      376382          90.9129
Filtered Sold       BelowGradeFinishedArea      411601          99.4198
Filtered Sold                 BusinessType      414003         100.0000
Filtered Sold                CoveredSpaces      414003         100.0000
Filtered Sold            LotSizeDimensions      393895          95.1430
Filtered Sold MiddleOrJuniorSchoolDistrict      414003         100.0000

Numeric distribution summary:
    variable  valid_count     min         max         mean   median       p1       p5      p25      p50       p75       p95       p99
  ClosePrice       414003    1.15 989500000.0 1.193847e+06 823000.0 202402.0 340000.0 575000.0 823000.0 1300000.0 2850000.0 5572900.0
  LivingArea       413769    0.00  17021321.0 1.903755e+03   1642.0    604.0    840.0   1248.0   1642.0    2219.0    3559.0    5282.0
DaysOnMarket       414003 -288.00     12430.0 3.735322e+01     18.0      0.0      1.0      8.0     18.0      48.0     132.0     231.0

All deliverable files saved:
- /content/drive/MyDrive/IDX-Exchange/output/week2_3_unique_property_types.csv
- /content/drive/MyDrive/IDX-Exchange/output/week2_3_null_count_summary.csv
- /content/drive/MyDrive/IDX-Exchange/output/week2_3_missing_over_90_percent.csv
- /content/drive/MyDrive/IDX-Exchange/output/week2_3_numeric_distribution_summary.csv
- /content/drive/MyDrive/IDX-Exchange/output/CRMLSSold_202401_202604_Residential_AnalysisFiltered.csv

Analysis dataset row counts:
Filtered Listing: 547,162
Filtered Sold: 414,003

Numeric distribution summary:
dataset              variable  valid_count  null_count     min          max         mean      median        p1          p5       p25         p50          p75          p95          p99
Listing            ClosePrice       137681      409481  525.00 8.200000e+08 1.203602e+06 850000.0000 213500.00 350000.0000 600000.00 850000.0000 1350000.0000 2.900000e+06 5.550000e+06
Listing             ListPrice       547162           0  100.00 4.000000e+08 1.315171e+06 848994.5000 211960.39 345000.0000 583002.50 848994.5000 1385000.0000 3.450000e+06 8.150000e+06
Listing     OriginalListPrice       546373         789    0.00 1.390000e+09 1.398709e+06 849000.0000 200000.00 348000.0000 585000.00 849000.0000 1395000.0000 3.495000e+06 8.499266e+06
Listing            LivingArea       546610         552    0.00 1.702132e+07 1.979898e+03   1670.0000    589.00    817.0000   1248.00   1670.0000    2300.0000 3.864000e+03 6.282000e+03
Listing          LotSizeAcres       502132       45030    0.00 4.187292e+06 6.421613e+01      0.1700      0.00      0.0287      0.12      0.1700       0.3122 3.560890e+00 1.344138e+01
Listing         BedroomsTotal       547029         133    0.00 9.400000e+01 3.225226e+00      3.0000      1.00      2.0000      2.00      3.0000       4.0000 5.000000e+00 6.000000e+00
Listing BathroomsTotalInteger       547107          55    0.00 2.208000e+03 2.626494e+00      2.0000      1.00      1.0000      2.00      2.0000       3.0000 5.000000e+00 7.000000e+00
Listing          DaysOnMarket       547162           0  -58.00 7.310000e+02 1.863006e+01     10.0000      0.00      0.0000      5.00     10.0000      21.0000 7.100000e+01 1.380000e+02
Listing             YearBuilt       546235         927 1776.00 2.028000e+03 1.979580e+03   1980.0000   1911.00   1929.0000   1961.00   1980.0000    2001.0000 2.023000e+03 2.025000e+03
   Sold            ClosePrice       414003           0    1.15 9.895000e+08 1.193847e+06 823000.0000 202402.00 340000.0000 575000.00 823000.0000 1300000.0000 2.850000e+06 5.572900e+06
   Sold             ListPrice       414003           0  525.00 1.375000e+08 1.140427e+06 815000.0000 214900.00 347000.0000 576000.00 815000.0000 1295000.0000 2.850000e+06 5.700000e+06
   Sold     OriginalListPrice       413247         756    0.00 1.390000e+09 1.225379e+06 825000.0000 210000.00 349900.0000 585000.00 825000.0000 1299000.0000 2.899999e+06 5.995000e+06
   Sold            LivingArea       413769         234    0.00 1.702132e+07 1.903755e+03   1642.0000    604.00    840.0000   1248.00   1642.0000    2219.0000 3.559000e+03 5.282000e+03
   Sold          LotSizeAcres       381472       32531    0.00 7.810698e+06 6.631124e+01      0.1664      0.00      0.0300      0.12      0.1664       0.2730 2.820000e+00 1.083350e+01
   Sold         BedroomsTotal       413992          11    0.00 4.500000e+01 3.200951e+00      3.0000      1.00      2.0000      3.00      3.0000       4.0000 5.000000e+00 6.000000e+00
   Sold BathroomsTotalInteger       413934          69    0.00 1.750000e+02 2.534682e+00      2.0000      1.00      1.0000      2.00      2.0000       3.0000 4.000000e+00 6.000000e+00
   Sold          DaysOnMarket       414003           0 -288.00 1.243000e+04 3.735322e+01     18.0000      0.00      1.0000      8.00     18.0000      48.0000 1.320000e+02 2.310000e+02
   Sold             YearBuilt       413631         372 1776.00 2.026000e+03 1.978582e+03   1979.0000   1912.00   1930.0000   1960.00   1979.0000    1999.0000 2.022000e+03 2.025000e+03

IQR outlier review:
dataset              variable        q1           q3         iqr  lower_iqr_fence  upper_iqr_fence  outliers_below  outliers_above  total_iqr_outliers  smallest_value  largest_value
Listing            ClosePrice 600000.00 1350000.0000 750000.0000     -525000.0000     2475000.0000               0            9944                9944          525.00   8.200000e+08
Listing             ListPrice 583002.50 1385000.0000 801997.5000     -619993.7500     2587996.2500               0           45935               45935          100.00   4.000000e+08
Listing     OriginalListPrice 585000.00 1395000.0000 810000.0000     -630000.0000     2610000.0000               0           45037               45037            0.00   1.390000e+09
Listing            LivingArea   1248.00    2300.0000   1052.0000        -330.0000        3878.0000               0           27011               27011            0.00   1.702132e+07
Listing          LotSizeAcres      0.12       0.3122      0.1922          -0.1683           0.6005               0           80487               80487            0.00   4.187292e+06
Listing         BedroomsTotal      2.00       4.0000      2.0000          -1.0000           7.0000               0            1751                1751            0.00   9.400000e+01
Listing BathroomsTotalInteger      2.00       3.0000      1.0000           0.5000           4.5000             687           33842               34529            0.00   2.208000e+03
Listing          DaysOnMarket      5.00      21.0000     16.0000         -19.0000          45.0000               4           48728               48732          -58.00   7.310000e+02
Listing             YearBuilt   1961.00    2001.0000     40.0000        1901.0000        2061.0000            1382               0                1382         1776.00   2.028000e+03
   Sold            ClosePrice 575000.00 1300000.0000 725000.0000     -512500.0000     2387500.0000               0           30768               30768            1.15   9.895000e+08
   Sold             ListPrice 576000.00 1295000.0000 719000.0000     -502500.0000     2373500.0000               0           31047               31047          525.00   1.375000e+08
   Sold     OriginalListPrice 585000.00 1299000.0000 714000.0000     -486000.0000     2370000.0000               0           32250               32250            0.00   1.390000e+09
   Sold            LivingArea   1248.00    2219.0000    971.0000        -208.5000        3675.5000               0           18202               18202            0.00   1.702132e+07
   Sold          LotSizeAcres      0.12       0.2730      0.1530          -0.1095           0.5025               0           59340               59340            0.00   7.810698e+06
   Sold         BedroomsTotal      3.00       4.0000      1.0000           1.5000           5.5000           15272            7452               22724            0.00   4.500000e+01
   Sold BathroomsTotalInteger      2.00       3.0000      1.0000           0.5000           4.5000             313           18725               19038            0.00   1.750000e+02
   Sold          DaysOnMarket      8.00      48.0000     40.0000         -52.0000         108.0000               8           31786               31794         -288.00   1.243000e+04
   Sold             YearBuilt   1960.00    1999.0000     39.0000        1901.5000        2057.5000             976               0                 976         1776.00   2.026000e+03

Updated deliverables:
- /content/drive/MyDrive/IDX-Exchange/output/CRMLSListing_202401_202604_Residential_AnalysisFiltered.csv
- /content/drive/MyDrive/IDX-Exchange/output/CRMLSSold_202401_202604_Residential_AnalysisFiltered.csv
- /content/drive/MyDrive/IDX-Exchange/output/week2_3_null_count_summary.csv
- /content/drive/MyDrive/IDX-Exchange/output/week2_3_missing_over_90_percent.csv
- /content/drive/MyDrive/IDX-Exchange/output/week2_3_numeric_distribution_summary.csv
- /content/drive/MyDrive/IDX-Exchange/output/week2_3_numeric_outlier_flags.csv
- /content/drive/MyDrive/IDX-Exchange/output/week2_3_numeric_plots (histograms and boxplots)

In [47]:
import pandas as pd
from pathlib import Path

output_dir = Path("/content/drive/MyDrive/IDX-Exchange/output")

listing_path = output_dir / (
    "CRMLSListing_202401_202604_Residential_AnalysisFiltered.csv"
)
sold_path = output_dir / (
    "CRMLSSold_202401_202604_Residential_AnalysisFiltered.csv"
)
types_path = output_dir / "week2_3_unique_property_types.csv"

listing = pd.read_csv(listing_path, low_memory=False)
sold = pd.read_csv(sold_path, low_memory=False)
types = pd.read_csv(types_path)

# Standardize numeric fields used in calculations.
for col in ["ClosePrice", "ListPrice"]:
    sold[col] = pd.to_numeric(sold[col], errors="coerce")

sold["CloseDate"] = pd.to_datetime(
    sold["CloseDate"], errors="coerce"
)

print("=" * 65)
print("1. RESIDENTIAL VS. OTHER PROPERTY TYPES")
print("=" * 65)

total_records = types["row_count"].sum()
types["share_percent"] = (
    types["row_count"] / total_records * 100
).round(2)

print(types.to_string(index=False))
residential_count = types.loc[
    types["PropertyType"].eq("Residential"), "row_count"
].sum()

print(f"\nTotal source records: {total_records:,}")
print(
    f"Residential: {residential_count:,} "
    f"({residential_count / total_records * 100:.2f}%)"
)
print(
    f"Other property types: {total_records - residential_count:,} "
    f"({(total_records - residential_count) / total_records * 100:.2f}%)"
)

print("\n" + "=" * 65)
print("2. CLOSE PRICE")
print("=" * 65)

prices = sold["ClosePrice"].dropna()
print(f"Valid closing prices: {len(prices):,}")
print(f"Median: ${prices.median():,.2f}")
print(f"Mean:   ${prices.mean():,.2f}")

print("\n" + "=" * 65)
print("3. DAYS ON MARKET")
print("=" * 65)

dom = pd.to_numeric(sold["DaysOnMarket"], errors="coerce").dropna()
print(f"Valid values: {len(dom):,}")
print(f"Mean: {dom.mean():,.2f} days")
print(f"Median: {dom.median():,.2f} days")
print(f"25th percentile: {dom.quantile(0.25):,.2f}")
print(f"75th percentile: {dom.quantile(0.75):,.2f}")
print(f"95th percentile: {dom.quantile(0.95):,.2f}")
print(f"Negative values: {(dom < 0).sum():,}")
print(f"Values over 3650 days: {(dom > 3650).sum():,}")

print("\n" + "=" * 65)
print("4. SOLD ABOVE VS. BELOW LIST PRICE")
print("=" * 65)

comparable = sold.loc[
    sold["ClosePrice"].gt(0) & sold["ListPrice"].gt(0),
    ["ClosePrice", "ListPrice"]
].dropna()

above = comparable["ClosePrice"] > comparable["ListPrice"]
below = comparable["ClosePrice"] < comparable["ListPrice"]
equal = comparable["ClosePrice"] == comparable["ListPrice"]
n = len(comparable)

print(f"Sales with valid closing and list prices: {n:,}")
print(f"Above list: {above.sum():,} ({above.mean() * 100:.2f}%)")
print(f"Below list: {below.sum():,} ({below.mean() * 100:.2f}%)")
print(f"Exactly list price: {equal.sum():,} ({equal.mean() * 100:.2f}%)")

print("\n" + "=" * 65)
print("5. POSSIBLE DATE CONSISTENCY ISSUES")
print("=" * 65)

date_columns = [
    col for col in sold.columns
    if "date" in col.lower() or "timestamp" in col.lower()
]
print("Date-related columns found:")
print(date_columns)

# Prefer a recognized listing/market date if present.
date_candidates = [
    "OnMarketDate",
    "ListingContractDate",
    "ListDate",
    "ListingDate",
    "OriginalEntryTimestamp",
    "ActivationDate",
    "PurchaseContractDate"
]

found_date = False

for col in date_candidates:
    if col not in sold.columns:
        continue

    listing_dates = pd.to_datetime(sold[col], errors="coerce")
    valid = listing_dates.notna() & sold["CloseDate"].notna()

    if valid.sum() == 0:
        continue

    before = valid & (sold["CloseDate"] < listing_dates)
    print(f"\nCandidate listing date: {col}")
    print(f"Comparable rows: {valid.sum():,}")
    print(
        "CloseDate earlier than this date: "
        f"{before.sum():,} ({before.sum() / valid.sum() * 100:.2f}%)"
    )

    if before.any():
        display(sold.loc[
            before,
            [c for c in [
                "ListingKey", "City", col, "CloseDate",
                "ClosePrice", "ListPrice"
            ] if c in sold.columns]
        ].head(10))

    found_date = True
    break

if not found_date:
    print(
        "No recognized listing-date field was found automatically. "
        "Use the printed date-related columns to select the correct "
        "listing/market date before drawing a conclusion."
    )

print("\n" + "=" * 65)
print("6. COUNTIES WITH THE HIGHEST MEDIAN CLOSING PRICES")
print("=" * 65)

county_candidates = [
    "CountyOrParish", "County", "CountyName"
]
county_col = next(
    (col for col in county_candidates if col in sold.columns),
    None
)

if county_col is None:
    print("No recognized county column found.")
    print(
        "Check the column names for a county field and rerun "
        "this section with the correct name."
    )
else:
    county_data = sold.loc[
        sold["ClosePrice"].gt(0)
        & sold[county_col].notna()
    ].copy()

    county_data[county_col] = (
        county_data[county_col].astype("string").str.strip()
    )
    county_data = county_data.loc[
        county_data[county_col].ne("")
    ]

    county_summary = (
        county_data.groupby(county_col)["ClosePrice"]
        .agg(median_close_price="median", sale_count="count")
        .reset_index()
    )

    # Require at least 30 sales to avoid rankings dominated by
    # counties with only a few observations.
    county_summary = county_summary.loc[
        county_summary["sale_count"] >= 30
    ].sort_values("median_close_price", ascending=False)

    print(f"County field used: {county_col}")
    print("Top 10 counties by median closing price (at least 30 sales):")
    display(county_summary.head(10))

    county_summary.to_csv(
        output_dir / "week2_3_county_median_prices.csv",
        index=False
    )
    print(
        "Saved county summary to "
        f"{output_dir / 'week2_3_county_median_prices.csv'}"
    )

=================================================================
1. RESIDENTIAL VS. OTHER PROPERTY TYPES
=================================================================
       PropertyType  row_count  share_percent
        Residential     961216          65.10
   ResidentialLease     319700          21.65
               Land      76319           5.17
  ResidentialIncome      48354           3.27
 ManufacturedInPark      41356           2.80
     CommercialSale      15525           1.05
    CommercialLease      10974           0.74
BusinessOpportunity       3161           0.21

Total source records: 1,476,605
Residential: 961,216 (65.10%)
Other property types: 515,389 (34.90%)

=================================================================
2. CLOSE PRICE
=================================================================
Valid closing prices: 414,003
Median: $823,000.00
Mean:   $1,193,847.08

=================================================================
3. DAYS ON MARKET
=================================================================
Valid values: 414,003
Mean: 37.35 days
Median: 18.00 days
25th percentile: 8.00
75th percentile: 48.00
95th percentile: 132.00
Negative values: 48
Values over 3650 days: 1

=================================================================
4. SOLD ABOVE VS. BELOW LIST PRICE
=================================================================
Sales with valid closing and list prices: 414,003
Above list: 166,010 (40.10%)
Below list: 176,150 (42.55%)
Exactly list price: 71,843 (17.35%)

=================================================================
5. POSSIBLE DATE CONSISTENCY ISSUES
=================================================================
Date-related columns found:
['CloseDate', 'ContractStatusChangeDate', 'PurchaseContractDate', 'ListingContractDate']

Candidate listing date: ListingContractDate
Comparable rows: 414,002
CloseDate earlier than this date: 61 (0.01%)

,ListingKey,City,ListingContractDate,CloseDate,ClosePrice,ListPrice
20,1059827487,Rancho Santa Fe,2024-01-31,2024-01-30,2160000.0,2195000.0
81,1059357897,Del Mar,2024-01-26,2024-01-25,2705000.0,2705000.0
710,1054052014,Oceanside,2024-01-02,2024-01-01,1600000.0,1600000.0
24270,1065738283,Newbury Park,2024-04-08,2024-03-29,1075000.0,1075000.0
24390,1063548623,San Diego,2024-03-21,2024-03-20,1650000.0,1595000.0
75925,1076675910,San Diego,2024-06-20,2024-06-13,715000.0,675000.0
110412,1079658093,La Jolla,2024-08-14,2024-08-13,5600000.0,5600000.0
129010,1080048344,Los Angeles,2024-10-02,2024-09-19,1305000.0,997000.0
129200,1079998553,Los Angeles,2024-09-30,2024-09-05,995000.0,995000.0
129834,1079658804,Los Angeles,2024-09-28,2024-09-24,1275000.0,1275000.0

=================================================================
6. COUNTIES WITH THE HIGHEST MEDIAN CLOSING PRICES
=================================================================
County field used: CountyOrParish
Top 10 counties by median closing price (at least 30 sales):

   CountyOrParish  median_close_price  sale_count
45      San Mateo           1700000.0        7277
47    Santa Clara           1600000.0       18452
48     Santa Cruz           1200000.0        2998
42  San Francisco           1198950.0         956
31         Orange           1175000.0       46594
22          Marin           1165000.0         146
0         Alameda           1134000.0       19532
28       Monterey            910000.0        3987
20    Los Angeles            900000.0      102884
41      San Diego            899000.0       51151

Saved county summary to /content/drive/MyDrive/IDX-Exchange/output/week2_3_county_median_prices.csv