<a href="https://colab.research.google.com/github/henryzhou24/IDX-Exchange-Data-Analyst/blob/main/IDX_Exchange_DA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import sys

print(sys.version)
print(sys.executable)

3.13.16 (main, Oct  1 2026, 15:40:24) [GCC 13.3.0]
/usr/bin/python3

In [5]:
import pandas as pd

print("Pandas version:", pd.__version__)

Pandas version: 2.2.3

In [6]:
from google.colab import drive

drive.mount('/content/drive')

Mounted at /content/drive

In [7]:
from pathlib import Path

project_dir = Path('/content/drive/MyDrive/IDX-Exchange')
data_dir = project_dir / 'data'

print("Project folder exists:", project_dir.exists())
print("Data folder exists:", data_dir.exists())

Project folder exists: True
Data folder exists: True

In [8]:
files = list(data_dir.iterdir())

print("Number of files:", len(files))

for file in files[:10]:
    print(file.name)

Number of files: 56
CRMLSListing202402.csv
CRMLSListing202401.csv
CRMLSListing202403.csv
CRMLSListing202404.csv
CRMLSListing202406.csv
CRMLSListing202405.csv
CRMLSListing202407.csv
CRMLSListing202408.csv
CRMLSListing202409.csv
CRMLSListing202410.csv

In [9]:
from collections import Counter

extensions = Counter(file.suffix.lower() for file in files)

print(extensions)

Counter({'.csv': 56})

In [10]:
listing_files = sorted(data_dir.glob("CRMLSListing*.csv"))
sold_files = sorted(data_dir.glob("CRMLSSold*.csv"))

print("Listing files:", len(listing_files))
print("Sold files:", len(sold_files))

print("\nListing files:")
for f in listing_files:
    print(f.name)

print("\nSold files:")
for f in sold_files:
    print(f.name)

Listing files: 28
Sold files: 28

Listing files:
CRMLSListing202401.csv
CRMLSListing202402.csv
CRMLSListing202403.csv
CRMLSListing202404.csv
CRMLSListing202405.csv
CRMLSListing202406.csv
CRMLSListing202407.csv
CRMLSListing202408.csv
CRMLSListing202409.csv
CRMLSListing202410.csv
CRMLSListing202411.csv
CRMLSListing202412.csv
CRMLSListing202501.csv
CRMLSListing202502.csv
CRMLSListing202503.csv
CRMLSListing202504.csv
CRMLSListing202505.csv
CRMLSListing202506.csv
CRMLSListing202507.csv
CRMLSListing202508.csv
CRMLSListing202509.csv
CRMLSListing202510.csv
CRMLSListing202511.csv
CRMLSListing202512.csv
CRMLSListing202601.csv
CRMLSListing202602.csv
CRMLSListing202603.csv
CRMLSListing202604.csv

Sold files:
CRMLSSold202401_filled.csv
CRMLSSold202402.csv
CRMLSSold202403_filled.csv
CRMLSSold202404_filled.csv
CRMLSSold202405_filled.csv
CRMLSSold202406_filled.csv
CRMLSSold202407_filled.csv
CRMLSSold202408.csv
CRMLSSold202409.csv
CRMLSSold202410.csv
CRMLSSold202411.csv
CRMLSSold202412.csv
CRMLSSold202501_filled.csv
CRMLSSold202502.csv
CRMLSSold202503.csv
CRMLSSold202504.csv
CRMLSSold202505.csv
CRMLSSold202506.csv
CRMLSSold202507.csv
CRMLSSold202508.csv
CRMLSSold202509.csv
CRMLSSold202510.csv
CRMLSSold202511.csv
CRMLSSold202512.csv
CRMLSSold202601.csv
CRMLSSold202602.csv
CRMLSSold202603.csv
CRMLSSold202604.csv

In [11]:
import pandas as pd

listing_file = listing_files[0]

print("File:", listing_file.name)

df_listing = pd.read_csv(listing_file)

print("Rows:", len(df_listing))
print("Columns:", len(df_listing.columns))

File: CRMLSListing202401.csv
Rows: 27454
Columns: 84

In [12]:
df_listing.head()

,OriginalListPrice,ListingKey,ListAgentEmail,CloseDate,ClosePrice,ListAgentFirstName,ListAgentLastName,Latitude,Longitude,UnparsedAddress,...,MainLevelBedrooms,NewConstructionYN,GarageSpaces,HighSchoolDistrict,PostalCode,BuyerOfficeName.1,AssociationFee,LotSizeSquareFeet,MiddleOrJuniorSchoolDistrict,UnparsedAddress.1
0,90000.0,1075010398,miriamlara03@gmail.com,NaN,NaN,Miriam,Lara,34.097939,-117.909653,1045 N Azusa 61,...,NaN,NaN,2.0,Covina Valley Unified,91722,NaN,0.0,NaN,NaN,1045 N Azusa 61
1,1500000.0,1074974457,janelle@judsonre.com,NaN,NaN,Janelle,Judson,33.121241,-117.081614,NaN,...,NaN,NaN,NaN,NaN,92025,NaN,0.0,NaN,NaN,NaN
2,1340000.0,1074973329,haleh360@Gmail.com,NaN,NaN,Haleh,Dowlatshahi,34.052207,-118.408445,2220 Avenue Of The Stars 2704,...,NaN,False,NaN,NaN,90067,NaN,2105.0,177861.0,NaN,2220 Avenue Of The Stars 2704
3,2500000.0,1074954552,Reneechen@yourhomesoldguaranteed.com,NaN,NaN,Renee,Chen,33.496363,-117.691677,16 Palisades,...,0.0,False,3.0,Capistrano Unified,92677,NaN,254.0,5300.0,NaN,16 Palisades
4,3150000.0,1074936537,anader@dppre.com,NaN,NaN,Margaret,Nader,34.119345,-118.111254,1615 Waverly Road,...,NaN,NaN,2.0,NaN,91108,NaN,NaN,9404.0,NaN,1615 Waverly Road

In [13]:
df_listing.columns.tolist()

['OriginalListPrice',
 'ListingKey',
 'ListAgentEmail',
 'CloseDate',
 'ClosePrice',
 'ListAgentFirstName',
 'ListAgentLastName',
 'Latitude',
 'Longitude',
 'UnparsedAddress',
 'PropertyType',
 'LivingArea',
 'ListPrice',
 'DaysOnMarket',
 'ListOfficeName',
 'BuyerOfficeName',
 'CoListOfficeName',
 'ListAgentFullName',
 'CoListAgentFirstName',
 'CoListAgentLastName',
 'BuyerAgentMlsId',
 'BuyerAgentFirstName',
 'BuyerAgentLastName',
 'FireplacesTotal',
 'AssociationFeeFrequency',
 'AboveGradeFinishedArea',
 'ListingKeyNumeric',
 'MLSAreaMajor',
 'TaxAnnualAmount',
 'CountyOrParish',
 'PropertyType.1',
 'MlsStatus',
 'ElementarySchool',
 'ListAgentFirstName.1',
 'AttachedGarageYN',
 'ParkingTotal',
 'BuilderName',
 'PropertySubType',
 'LotSizeAcres',
 'SubdivisionName',
 'BuyerOfficeAOR',
 'YearBuilt',
 'DaysOnMarket.1',
 'BuyerAgencyCompensationType',
 'StreetNumberNumeric',
 'LivingArea.1',
 'ListingId',
 'BathroomsTotalInteger',
 'City',
 'BuyerAgencyCompensation',
 'TaxYear',
 'BuildingAreaTotal',
 'BedroomsTotal',
 'ContractStatusChangeDate',
 'Longitude.1',
 'ElementarySchoolDistrict',
 'CoBuyerAgentFirstName',
 'PurchaseContractDate',
 'ListingContractDate',
 'BelowGradeFinishedArea',
 'BusinessType',
 'Latitude.1',
 'ListPrice.1',
 'StateOrProvince',
 'CoveredSpaces',
 'MiddleOrJuniorSchool',
 'FireplaceYN',
 'Stories',
 'HighSchool',
 'Levels',
 'ListAgentLastName.1',
 'CloseDate.1',
 'LotSizeDimensions',
 'LotSizeArea',
 'MainLevelBedrooms',
 'NewConstructionYN',
 'GarageSpaces',
 'HighSchoolDistrict',
 'PostalCode',
 'BuyerOfficeName.1',
 'AssociationFee',
 'LotSizeSquareFeet',
 'MiddleOrJuniorSchoolDistrict',
 'UnparsedAddress.1']

In [14]:
df_listing.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27454 entries, 0 to 27453
Data columns (total 84 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   OriginalListPrice             27349 non-null  float64
 1   ListingKey                    27454 non-null  int64
 2   ListAgentEmail                27421 non-null  object
 3   CloseDate                     20136 non-null  object
 4   ClosePrice                    20001 non-null  float64
 5   ListAgentFirstName            27292 non-null  object
 6   ListAgentLastName             27451 non-null  object
 7   Latitude                      22233 non-null  float64
 8   Longitude                     22271 non-null  float64
 9   UnparsedAddress               27393 non-null  object
 10  PropertyType                  27454 non-null  object
 11  LivingArea                    23743 non-null  float64
 12  ListPrice                     27381 non-null  float64
 13  DaysOnMarket                  27454 non-null  int64
 14  ListOfficeName                27454 non-null  object
 15  BuyerOfficeName               19806 non-null  object
 16  CoListOfficeName              5640 non-null   object
 17  ListAgentFullName             27450 non-null  object
 18  CoListAgentFirstName          5591 non-null   object
 19  CoListAgentLastName           5602 non-null   object
 20  BuyerAgentMlsId               20057 non-null  object
 21  BuyerAgentFirstName           19985 non-null  object
 22  BuyerAgentLastName            20080 non-null  object
 23  FireplacesTotal               0 non-null      float64
 24  AssociationFeeFrequency       7831 non-null   object
 25  AboveGradeFinishedArea        0 non-null      float64
 26  ListingKeyNumeric             27454 non-null  int64
 27  MLSAreaMajor                  24798 non-null  object
 28  TaxAnnualAmount               219 non-null    float64
 29  CountyOrParish                27454 non-null  object
 30  PropertyType.1                27454 non-null  object
 31  MlsStatus                     27454 non-null  object
 32  ElementarySchool              2616 non-null   object
 33  ListAgentFirstName.1          27292 non-null  object
 34  AttachedGarageYN              18072 non-null  object
 35  ParkingTotal                  25408 non-null  float64
 36  BuilderName                   950 non-null    object
 37  PropertySubType               23689 non-null  object
 38  LotSizeAcres                  24588 non-null  float64
 39  SubdivisionName               9144 non-null   object
 40  BuyerOfficeAOR                19485 non-null  object
 41  YearBuilt                     24912 non-null  float64
 42  DaysOnMarket.1                27454 non-null  int64
 43  BuyerAgencyCompensationType   27435 non-null  object
 44  StreetNumberNumeric           27333 non-null  float64
 45  LivingArea.1                  23743 non-null  float64
 46  ListingId                     27454 non-null  object
 47  BathroomsTotalInteger         24913 non-null  float64
 48  City                          27408 non-null  object
 49  BuyerAgencyCompensation       27415 non-null  float64
 50  TaxYear                       37 non-null     float64
 51  BuildingAreaTotal             4168 non-null   float64
 52  BedroomsTotal                 23857 non-null  float64
 53  ContractStatusChangeDate      27314 non-null  object
 54  Longitude.1                   22271 non-null  float64
 55  ElementarySchoolDistrict      0 non-null      float64
 56  CoBuyerAgentFirstName         1669 non-null   object
 57  PurchaseContractDate          21281 non-null  object
 58  ListingContractDate           27454 non-null  object
 59  BelowGradeFinishedArea        72 non-null     float64
 60  BusinessType                  227 non-null    object
 61  Latitude.1                    22233 non-null  float64
 62  ListPrice.1                   27381 non-null  float64
 63  StateOrProvince               27452 non-null  object
 64  CoveredSpaces                 0 non-null      float64
 65  MiddleOrJuniorSchool          2662 non-null   object
 66  FireplaceYN                   23126 non-null  object
 67  Stories                       20230 non-null  float64
 68  HighSchool                    3459 non-null   object
 69  Levels                        21929 non-null  object
 70  ListAgentLastName.1           27451 non-null  object
 71  CloseDate.1                   20136 non-null  object
 72  LotSizeDimensions             1507 non-null   object
 73  LotSizeArea                   24701 non-null  float64
 74  MainLevelBedrooms             12990 non-null  float64
 75  NewConstructionYN             23627 non-null  object
 76  GarageSpaces                  22053 non-null  float64
 77  HighSchoolDistrict            16671 non-null  object
 78  PostalCode                    27444 non-null  object
 79  BuyerOfficeName.1             19806 non-null  object
 80  AssociationFee                18889 non-null  float64
 81  LotSizeSquareFeet             24659 non-null  float64
 82  MiddleOrJuniorSchoolDistrict  0 non-null      float64
 83  UnparsedAddress.1             27393 non-null  object
dtypes: float64(32), int64(4), object(48)
memory usage: 17.6+ MB

In [15]:
df_listing.isna().sum().sort_values(ascending=False).head(20)

ElementarySchoolDistrict        27454
CoveredSpaces                   27454
AboveGradeFinishedArea          27454
FireplacesTotal                 27454
MiddleOrJuniorSchoolDistrict    27454
TaxYear                         27417
BelowGradeFinishedArea          27382
TaxAnnualAmount                 27235
BusinessType                    27227
BuilderName                     26504
LotSizeDimensions               25947
CoBuyerAgentFirstName           25785
ElementarySchool                24838
MiddleOrJuniorSchool            24792
HighSchool                      23995
BuildingAreaTotal               23286
CoListAgentFirstName            21863
CoListAgentLastName             21852
CoListOfficeName                21814
AssociationFeeFrequency         19623
dtype: int64

In [16]:
sold_file = sold_files[0]

print("File:", sold_file.name)

df_sold = pd.read_csv(sold_file)

print("Rows:", len(df_sold))
print("Columns:", len(df_sold.columns))

File: CRMLSSold202401_filled.csv
Rows: 17958
Columns: 80

In [17]:
df_sold.head()

,Flooring,ViewYN,WaterfrontYN,BasementYN,PoolPrivateYN,OriginalListPrice,ListingKey,ListAgentEmail,CloseDate,ClosePrice,...,MainLevelBedrooms,NewConstructionYN,GarageSpaces,HighSchoolDistrict,PostalCode,AssociationFee,LotSizeSquareFeet,MiddleOrJuniorSchoolDistrict,latfilled,lonfilled
0,"Carpet,Tile,Wood",True,NaN,NaN,False,499000.0,551985747,jwachter@cbnorcal.com,2024-01-26,240000.0,...,NaN,False,1.0,Other,94401,6472.0,NaN,NaN,True,True
1,NaN,NaN,NaN,NaN,NaN,0.0,535486633,eabrown@lee-associates.com,2024-01-24,950.0,...,NaN,NaN,NaN,NaN,92394,NaN,52320.0,NaN,False,False
2,NaN,True,NaN,NaN,NaN,75000.0,529986282,Joe@9WINWIN.com,2024-01-16,45000.0,...,NaN,False,NaN,NaN,93240,NaN,217364.0,NaN,False,False
3,NaN,True,NaN,NaN,NaN,199000.0,529618166,carolthefinder@yahoo.com,2024-01-08,141500.0,...,NaN,False,NaN,NaN,92308,NaN,217800.0,NaN,False,False
4,NaN,True,NaN,NaN,NaN,19500.0,522614340,jtavisola@tavisola.com,2024-01-17,15000.0,...,NaN,False,NaN,NaN,93544,0.0,108883.0,NaN,False,False

In [18]:
print(df_sold.columns.tolist())

['Flooring', 'ViewYN', 'WaterfrontYN', 'BasementYN', 'PoolPrivateYN', 'OriginalListPrice', 'ListingKey', 'ListAgentEmail', 'CloseDate', 'ClosePrice', 'ListAgentFirstName', 'ListAgentLastName', 'Latitude', 'Longitude', 'UnparsedAddress', 'PropertyType', 'LivingArea', 'ListPrice', 'DaysOnMarket', 'ListOfficeName', 'BuyerOfficeName', 'CoListOfficeName', 'ListAgentFullName', 'CoListAgentFirstName', 'CoListAgentLastName', 'BuyerAgentMlsId', 'BuyerAgentFirstName', 'BuyerAgentLastName', 'FireplacesTotal', 'AssociationFeeFrequency', 'AboveGradeFinishedArea', 'ListingKeyNumeric', 'MLSAreaMajor', 'TaxAnnualAmount', 'CountyOrParish', 'MlsStatus', 'ElementarySchool', 'AttachedGarageYN', 'ParkingTotal', 'BuilderName', 'PropertySubType', 'LotSizeAcres', 'SubdivisionName', 'BuyerOfficeAOR', 'YearBuilt', 'BuyerAgencyCompensationType', 'StreetNumberNumeric', 'ListingId', 'BathroomsTotalInteger', 'City', 'BuyerAgencyCompensation', 'TaxYear', 'BuildingAreaTotal', 'BedroomsTotal', 'ContractStatusChangeDate', 'ElementarySchoolDistrict', 'CoBuyerAgentFirstName', 'PurchaseContractDate', 'ListingContractDate', 'BelowGradeFinishedArea', 'BusinessType', 'StateOrProvince', 'CoveredSpaces', 'MiddleOrJuniorSchool', 'FireplaceYN', 'Stories', 'HighSchool', 'Levels', 'LotSizeDimensions', 'LotSizeArea', 'MainLevelBedrooms', 'NewConstructionYN', 'GarageSpaces', 'HighSchoolDistrict', 'PostalCode', 'AssociationFee', 'LotSizeSquareFeet', 'MiddleOrJuniorSchoolDistrict', 'latfilled', 'lonfilled']

In [19]:
df_sold.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17958 entries, 0 to 17957
Data columns (total 80 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Flooring                      10104 non-null  object
 1   ViewYN                        16198 non-null  object
 2   WaterfrontYN                  10 non-null     object
 3   BasementYN                    265 non-null    object
 4   PoolPrivateYN                 15447 non-null  object
 5   OriginalListPrice             17900 non-null  float64
 6   ListingKey                    17958 non-null  int64
 7   ListAgentEmail                17939 non-null  object
 8   CloseDate                     17958 non-null  object
 9   ClosePrice                    17958 non-null  float64
 10  ListAgentFirstName            17852 non-null  object
 11  ListAgentLastName             17956 non-null  object
 12  Latitude                      17927 non-null  float64
 13  Longitude                     17928 non-null  float64
 14  UnparsedAddress               17922 non-null  object
 15  PropertyType                  17958 non-null  object
 16  LivingArea                    16410 non-null  float64
 17  ListPrice                     17924 non-null  float64
 18  DaysOnMarket                  17958 non-null  int64
 19  ListOfficeName                17958 non-null  object
 20  BuyerOfficeName               17737 non-null  object
 21  CoListOfficeName              3432 non-null   object
 22  ListAgentFullName             17956 non-null  object
 23  CoListAgentFirstName          3407 non-null   object
 24  CoListAgentLastName           3417 non-null   object
 25  BuyerAgentMlsId               17924 non-null  object
 26  BuyerAgentFirstName           17874 non-null  object
 27  BuyerAgentLastName            17955 non-null  object
 28  FireplacesTotal               0 non-null      float64
 29  AssociationFeeFrequency       4933 non-null   object
 30  AboveGradeFinishedArea        0 non-null      float64
 31  ListingKeyNumeric             17958 non-null  int64
 32  MLSAreaMajor                  16220 non-null  object
 33  TaxAnnualAmount               108 non-null    float64
 34  CountyOrParish                17958 non-null  object
 35  MlsStatus                     17958 non-null  object
 36  ElementarySchool              1822 non-null   object
 37  AttachedGarageYN              12508 non-null  object
 38  ParkingTotal                  16743 non-null  float64
 39  BuilderName                   691 non-null    object
 40  PropertySubType               16296 non-null  object
 41  LotSizeAcres                  16100 non-null  float64
 42  SubdivisionName               6187 non-null   object
 43  BuyerOfficeAOR                17450 non-null  object
 44  YearBuilt                     17024 non-null  float64
 45  BuyerAgencyCompensationType   17930 non-null  object
 46  StreetNumberNumeric           17892 non-null  float64
 47  ListingId                     17958 non-null  object
 48  BathroomsTotalInteger         16884 non-null  float64
 49  City                          17939 non-null  object
 50  BuyerAgencyCompensation       17942 non-null  float64
 51  TaxYear                       18 non-null     float64
 52  BuildingAreaTotal             2466 non-null   float64
 53  BedroomsTotal                 16457 non-null  float64
 54  ContractStatusChangeDate      17241 non-null  object
 55  ElementarySchoolDistrict      0 non-null      float64
 56  CoBuyerAgentFirstName         1365 non-null   object
 57  PurchaseContractDate          17536 non-null  object
 58  ListingContractDate           17956 non-null  object
 59  BelowGradeFinishedArea        54 non-null     float64
 60  BusinessType                  66 non-null     object
 61  StateOrProvince               17958 non-null  object
 62  CoveredSpaces                 0 non-null      float64
 63  MiddleOrJuniorSchool          1855 non-null   object
 64  FireplaceYN                   16072 non-null  object
 65  Stories                       14099 non-null  float64
 66  HighSchool                    2464 non-null   object
 67  Levels                        15163 non-null  object
 68  LotSizeDimensions             952 non-null    object
 69  LotSizeArea                   16163 non-null  float64
 70  MainLevelBedrooms             9392 non-null   float64
 71  NewConstructionYN             15653 non-null  object
 72  GarageSpaces                  15361 non-null  float64
 73  HighSchoolDistrict            11835 non-null  object
 74  PostalCode                    17946 non-null  object
 75  AssociationFee                12275 non-null  float64
 76  LotSizeSquareFeet             16146 non-null  float64
 77  MiddleOrJuniorSchoolDistrict  0 non-null      float64
 78  latfilled                     17958 non-null  bool
 79  lonfilled                     17958 non-null  bool
dtypes: bool(2), float64(28), int64(3), object(47)
memory usage: 10.7+ MB

In [20]:
listing_cols = set(df_listing.columns)
sold_cols = set(df_sold.columns)

print("Columns only in Listing:")
print(sorted(list(listing_cols - sold_cols)))

print("\nColumns only in Sold:")
print(sorted(list(sold_cols - listing_cols)))

print("\nCommon columns:", len(listing_cols & sold_cols))

Columns only in Listing:
['BuyerOfficeName.1', 'CloseDate.1', 'DaysOnMarket.1', 'Latitude.1', 'ListAgentFirstName.1', 'ListAgentLastName.1', 'ListPrice.1', 'LivingArea.1', 'Longitude.1', 'PropertyType.1', 'UnparsedAddress.1']

Columns only in Sold:
['BasementYN', 'Flooring', 'PoolPrivateYN', 'ViewYN', 'WaterfrontYN', 'latfilled', 'lonfilled']

Common columns: 73

In [21]:
filled_sold = data_dir / "CRMLSSold202401_filled.csv"
normal_sold = data_dir / "CRMLSSold202402.csv"

df_filled = pd.read_csv(filled_sold)
df_normal = pd.read_csv(normal_sold)

print("202401 filled:")
print(df_filled.shape)

print("\n202402 normal:")
print(df_normal.shape)

202401 filled:
(17958, 80)

202402 normal:
(19925, 78)

In [22]:
print("Filled columns:", len(df_filled.columns))
print("Normal columns:", len(df_normal.columns))

print("\nColumns only in filled:")
print(sorted(list(set(df_filled.columns) - set(df_normal.columns))))

print("\nColumns only in normal:")
print(sorted(list(set(df_normal.columns) - set(df_filled.columns))))

Filled columns: 80
Normal columns: 78

Columns only in filled:
['latfilled', 'lonfilled']

Columns only in normal:
[]

**Check ListingKey uniqueness**

In [23]:
print("Listing rows:", len(df_listing))
print("Unique ListingKey:", df_listing["ListingKey"].nunique())

print("Duplicate ListingKey rows:",
      df_listing["ListingKey"].duplicated().sum())

Listing rows: 27454
Unique ListingKey: 27454
Duplicate ListingKey rows: 0

In [24]:
print("Sold rows:", len(df_sold))
print("Unique ListingKey:", df_sold["ListingKey"].nunique())

print("Duplicate ListingKey rows:",
      df_sold["ListingKey"].duplicated().sum())

Sold rows: 17958
Unique ListingKey: 17958
Duplicate ListingKey rows: 0

**Check whether ListingKey overlaps**

In [25]:
listing_keys = set(df_listing["ListingKey"].dropna())
sold_keys = set(df_sold["ListingKey"].dropna())

overlap = listing_keys & sold_keys

print("Listing keys:", len(listing_keys))
print("Sold keys:", len(sold_keys))
print("Keys appearing in BOTH:", len(overlap))

Listing keys: 27454
Sold keys: 17958
Keys appearing in BOTH: 1977

In [26]:
print(
    "Percentage of Sold records also found in Listing:",
    round(len(overlap) / len(sold_keys) * 100, 2),
    "%"
)

Percentage of Sold records also found in Listing: 11.01 %

**Look at one matching property**

In [27]:
if overlap:
    example_key = next(iter(overlap))

    listing_match = df_listing[
        df_listing["ListingKey"] == example_key
    ]

    sold_match = df_sold[
        df_sold["ListingKey"] == example_key
    ]

    print("Example ListingKey:", example_key)

    print("\n--- LISTING ---")
    display(
        listing_match[
            ["ListingKey", "ListPrice", "OriginalListPrice",
             "ListingContractDate", "CloseDate", "ClosePrice",
             "MlsStatus", "City"]
        ]
    )

    print("\n--- SOLD ---")
    display(
        sold_match[
            ["ListingKey", "ListPrice", "OriginalListPrice",
             "ListingContractDate", "CloseDate", "ClosePrice",
             "MlsStatus", "City"]
        ]
    )

Example ListingKey: 1054105600

--- LISTING ---

,ListingKey,ListPrice,OriginalListPrice,ListingContractDate,CloseDate,ClosePrice,MlsStatus,City
25124,1054105600,3550.0,3550.0,2024-01-04,2024-01-08,3495.0,Closed,Santa Monica

--- SOLD ---

,ListingKey,ListPrice,OriginalListPrice,ListingContractDate,CloseDate,ClosePrice,MlsStatus,City
1718,1054105600,3550.0,3550.0,2024-01-04,2024-01-08,3495.0,Closed,Santa Monica

**Confirm the Residential category**

In [ ]:
# Check the PropertyType values in one Listing and one Sold file

print("Listing PropertyType values:")
print(df_listing["PropertyType"].value_counts(dropna=False).head(20))

print("\nSold PropertyType values:")
print(df_sold["PropertyType"].value_counts(dropna=False).head(20))

Listing PropertyType values:
PropertyType
Residential            17007
ResidentialLease        5752
Land                    2145
ResidentialIncome        893
ManufacturedInPark       877
CommercialSale           394
CommercialLease          291
BusinessOpportunity       95
Name: count, dtype: int64

Sold PropertyType values:
PropertyType
Residential            11194
ResidentialLease        4672
Land                     778
ResidentialIncome        524
ManufacturedInPark       515
CommercialSale           127
CommercialLease          126
BusinessOpportunity       22
Name: count, dtype: int64

**Create the output folder**

In [ ]:
output_dir = project_dir / "output"
output_dir.mkdir(parents=True, exist_ok=True)

print("Output folder:", output_dir)
print("Folder exists:", output_dir.exists())

Output folder: /content/drive/MyDrive/IDX-Exchange/output
Folder exists: True

**Combine, filter, and export**

In [ ]:

import pandas as pd
from pathlib import Path

# Discover the monthly source files
listing_files = sorted(data_dir.glob("CRMLSListing*.csv"))
sold_files = sorted(data_dir.glob("CRMLSSold*.csv"))

print(f"Listing files found: {len(listing_files)}")
print(f"Sold files found: {len(sold_files)}")

# Check that we have the expected monthly coverage
assert len(listing_files) == 28, (
    f"Expected 28 Listing files, found {len(listing_files)}"
)
assert len(sold_files) == 28, (
    f"Expected 28 Sold files, found {len(sold_files)}"
)

def process_monthly_files(files, dataset_name, output_filename):
    monthly_data = []
    file_counts = []

    for file in files:
        df = pd.read_csv(file)

        if "PropertyType" not in df.columns:
            raise ValueError(
                f"'PropertyType' missing from {file.name}"
            )

        rows_before = len(df)

        # Filter to the required property category
        residential = df[
            df["PropertyType"].astype("string").str.strip()
            == "Residential"
        ].copy()

        rows_after = len(residential)

        file_counts.append({
            "dataset": dataset_name,
            "filename": file.name,
            "rows_before_filter": rows_before,
            "residential_rows": rows_after,
            "rows_removed": rows_before - rows_after
        })

        monthly_data.append(residential)

    # Combine the filtered monthly files
    combined = pd.concat(monthly_data, ignore_index=True)

    # Save the combined residential dataset
    output_path = output_dir / output_filename
    combined.to_csv(output_path, index=False)

    summary = {
        "dataset": dataset_name,
        "files_processed": len(files),
        "rows_before_filter": sum(
            x["rows_before_filter"] for x in file_counts
        ),
        "residential_rows": len(combined),
        "rows_removed": sum(
            x["rows_removed"] for x in file_counts
        ),
        "columns_in_output": len(combined.columns),
        "output_file": output_filename
    }

    print(f"\n{dataset_name}")
    print("-" * 40)
    print(f"Files processed: {summary['files_processed']:,}")
    print(f"Rows before filtering: {summary['rows_before_filter']:,}")
    print(f"Residential rows: {summary['residential_rows']:,}")
    print(f"Rows removed: {summary['rows_removed']:,}")
    print(f"Output columns: {summary['columns_in_output']:,}")
    print(f"Saved to: {output_path}")

    return combined, summary, file_counts


# Process Listing files
listing_residential, listing_summary, listing_counts = (
    process_monthly_files(
        listing_files,
        "Listing",
        "CRMLSListing_202401_202604_Residential.csv"
    )
)

# Process Sold files
sold_residential, sold_summary, sold_counts = (
    process_monthly_files(
        sold_files,
        "Sold",
        "CRMLSSold_202401_202604_Residential.csv"
    )
)

# Save processing documentation
summary_df = pd.DataFrame([listing_summary, sold_summary])
counts_df = pd.DataFrame(listing_counts + sold_counts)

summary_df.to_csv(
    output_dir / "week1_processing_summary.csv",
    index=False
)
counts_df.to_csv(
    output_dir / "week1_monthly_file_counts.csv",
    index=False
)

display(summary_df)
print("\nWeek 1 processing complete.")

Listing files found: 28
Sold files found: 28

/tmp/ipykernel_1696/1271434387.py:24: DtypeWarning: Columns (32,58,63,66) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)

Listing
----------------------------------------
Files processed: 28
Rows before filtering: 860,898
Residential rows: 547,162
Rows removed: 313,736
Output columns: 84
Saved to: /content/drive/MyDrive/IDX-Exchange/output/CRMLSListing_202401_202604_Residential.csv

/tmp/ipykernel_1696/1271434387.py:24: DtypeWarning: Columns (2,36,39,56,74) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)
/tmp/ipykernel_1696/1271434387.py:24: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)
/tmp/ipykernel_1696/1271434387.py:24: DtypeWarning: Columns (4,74) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)

Sold
----------------------------------------
Files processed: 28
Rows before filtering: 615,707
Residential rows: 414,054
Rows removed: 201,653
Output columns: 84
Saved to: /content/drive/MyDrive/IDX-Exchange/output/CRMLSSold_202401_202604_Residential.csv

,dataset,files_processed,rows_before_filter,residential_rows,rows_removed,columns_in_output,output_file
0,Listing,28,860898,547162,313736,84,CRMLSListing_202401_202604_Residential.csv
1,Sold,28,615707,414054,201653,84,CRMLSSold_202401_202604_Residential.csv

Week 1 processing complete.

**Validate the outputs**

In [28]:
from pathlib import Path
import pandas as pd

project_dir = Path("/content/drive/MyDrive/IDX-Exchange")
output_dir = project_dir / "output"

print("Output folder exists:", output_dir.exists())
print("Output files:", [p.name for p in output_dir.glob("*.csv")])

Output folder exists: True
Output files: ['CRMLSListing_202401_202604_Residential.csv', 'CRMLSSold_202401_202604_Residential.csv', 'week1_processing_summary.csv', 'week1_monthly_file_counts.csv']

In [29]:

import pandas as pd

listing_output = output_dir / "CRMLSListing_202401_202604_Residential.csv"
sold_output = output_dir / "CRMLSSold_202401_202604_Residential.csv"

expected_rows = {
    listing_output.name: 547_162,
    sold_output.name: 414_054
}

for path in [listing_output, sold_output]:
    print(f"\nChecking: {path.name}")
    assert path.exists(), f"File not found: {path}"

    check = pd.read_csv(path, low_memory=False)

    non_residential = (
        check["PropertyType"].astype("string").str.strip() != "Residential"
    ).sum()

    print(f"Rows: {len(check):,}")
    print(f"Columns: {len(check.columns):,}")
    print(f"Non-residential rows: {non_residential:,}")
    print(f"Matches expected row count: {len(check) == expected_rows[path.name]}")

    assert len(check) == expected_rows[path.name], "Unexpected row count"
    assert non_residential == 0, "Non-residential rows remain"

print("\nSUCCESS: Both output files passed validation.")

Checking: CRMLSListing_202401_202604_Residential.csv
Rows: 547,162
Columns: 84
Non-residential rows: 0
Matches expected row count: True

Checking: CRMLSSold_202401_202604_Residential.csv
Rows: 414,054
Columns: 84
Non-residential rows: 0
Matches expected row count: True

SUCCESS: Both output files passed validation.